export const WHATSAPP_NUMBER = "2348140874503";

export function getWhatsAppLink(productName: string): string {
  const message = `Hello Dr I've Read And I Want To Place Order For Your ${productName} Treatment Pack!`;
  return `https://api.whatsapp.com/send?phone=${WHATSAPP_NUMBER}&text=${encodeURIComponent(message)}`;
}

export interface PricingPack {
  label: string;
  bottles: number;
  originalPrice: number;
  salePrice: number;
  description: string;
  recommended?: boolean;
  includedProducts?: string[];
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  heroHeadline: string;
  heroSubheadline: string;
  productName: string;
  whatsappKeyword: string;
  color: string;
  icon: string;
  images: string[];
  pricingPacks: PricingPack[];
  symptoms: string[];
  benefits: string[];
  faqs: { q: string; a: string }[];
  testimonials: { name: string; location: string; text: string; rating: number }[];
  // New enriched content fields
  educationalIntro?: string;
  rootCauses?: string[];
  howItWorks?: string;
  detailedBenefits?: { title: string; description: string }[];
  warningNote?: string;
}

export const products: Product[] = [
  {
    id: "ed",
    slug: "ed-sexual-health",
    name: "ED & Sexual Health",
    tagline: "Rock-Hard Performance, Naturally",
    heroHeadline: "End Erectile Dysfunction & Last Over 50 Minutes In Bed",
    heroSubheadline: "Reodeo/Vigormax Capsules — 100% herbal, NAFDAC approved, zero side effects",
    productName: "Reodeo/Vigormax Capsules",
    whatsappKeyword: "WEAK ERECTION",
    color: "rose",
    icon: "Activity",
    images: [
      "/images/products/ed/ed-1.png",
      "/images/products/ed/ed-2.png",
      "/images/products/ed/ed-3.png",
      "/images/products/ed/ed-7.png",
    ],
    educationalIntro: "Erectile Dysfunction (ED) is a condition that crushes the confidence, ego, and happiness of a grown man — and it affects millions of Nigerian men across all age groups. Whether it's weak erections, premature ejaculation (finishing in under 1 minute), or complete loss of sexual desire, ED can silently destroy relationships and self-esteem. The good news? It doesn't have to be permanent.",
    rootCauses: [
      "Temporary depression & chronic stress",
      "Underlying infections (Staph, STDs)",
      "Prostatitis or prostate enlargement",
      "Heart disease & clogged blood vessels",
      "High cholesterol & high blood pressure",
      "Diabetes (Type 1 & Type 2)",
      "Obesity & poor nutrition",
      "Alcoholism & substance abuse",
      "Drug abuse (pharma-based pills like Viagra/Cialis)",
    ],
    howItWorks: "Reodeo/Vigormax Capsules is a naturally fortified solution that combines the power of ancient herbs to support optimum performance of the male sexual organ. It is non-hormonal and never addictive. Unlike pharmaceutical drugs like Viagra or Cialis that only provide temporary relief with dangerous side effects, this herbal formula performs a gradual corrective function — even if you have diabetes or high blood pressure. Over 6,000 men between ages 30 and 80 have used this product since 2013, all with documented success.",
    detailedBenefits: [
      { title: "Restores Strong Erections", description: "Permanently restores your ability to maintain rock-hard erections — not a temporary fix like pharma pills." },
      { title: "Ends Premature Ejaculation", description: "Go from finishing in under 1 minute to lasting 50+ minutes per round, naturally and consistently." },
      { title: "Boosts Sperm Count & Libido", description: "Enhances male libido, increases sperm production, and supports healthy testosterone levels." },
      { title: "Works With Underlying Conditions", description: "Unlike other solutions, it works even if you have diabetes, high blood pressure, or high cholesterol." },
      { title: "Supports Prostate Health", description: "Also helps with prostate symptoms like frequent urination, supporting overall male reproductive health." },
      { title: "Zero Side Effects", description: "100% pure herbal blend — no chemicals, no addiction, no dependency. Safe for long-term use." },
    ],
    warningNote: "This product is designed for men who are ready to make permanent changes to their sexual health. It is a corrective therapy, not a one-time stimulant.",
    pricingPacks: [
      { label: "Mini Pack", bottles: 2, originalPrice: 53500, salePrice: 43500, description: "Good for mild cases or first-timers", includedProducts: ["1 Reodeo", "1 Vigo Max"] },
      { label: "Medium Pack", bottles: 3, originalPrice: 69500, salePrice: 59500, description: "Most popular — significant improvement", recommended: true, includedProducts: ["2 Reodeo", "1 Vigo Max"] },
      { label: "Max Pack", bottles: 4, originalPrice: 85500, salePrice: 75500, description: "Deep corrective therapy, lasting results", includedProducts: ["2 Reodeo", "1 Royal Jelly", "1 Zinc"] },
      { label: "Severe Pack", bottles: 5, originalPrice: 97500, salePrice: 89000, description: "For long-term or severe ED conditions", includedProducts: ["3 Reodeo", "1 Vigo Max", "1 Zinc"] },
    ],
    symptoms: [
      "Weak or no erection at all",
      "Premature ejaculation (finishing under 1 minute)",
      "Complete loss of interest in sex",
      "Unable to maintain erection during foreplay",
      "Erection drops immediately after penetration",
      "Cannot achieve a second round for 24+ hours",
      "Partner dissatisfaction & relationship strain",
      "Low confidence & anxiety in the bedroom",
    ],
    benefits: [
      "Rock-hard erections restored permanently",
      "Lasts 50+ minutes per round",
      "Boosts sperm count & libido",
      "Ends premature ejaculation",
      "100% herbal — no side effects",
      "Works even with diabetes or hypertension",
      "Non-addictive, no pharma chemicals",
      "Improved testosterone levels",
      "Supports immune system",
      "Promotes vitality & endurance",
    ],
    faqs: [
      { q: "Does this product really work?", a: "Yes! Over 6,000 men have used it since 2013 with documented success. It has been personally prescribed by health practitioners to men between ages 30–80 with consistent positive results." },
      { q: "How many bottles do I need?", a: "2 bottles is a good start for mild cases. For permanent results and severe conditions, we recommend 3–5 bottles depending on severity." },
      { q: "Does it have side effects?", a: "No. It's a 100% pure herbal blend with no chemicals, no additives, and no dependency. It's completely safe for long-term use." },
      { q: "Can I use it with my current medications?", a: "We recommend using it alone to see full effectiveness. Consult your doctor if currently on prescription drugs." },
      { q: "How long before I see results?", a: "Most customers notice significant changes within the first 2–3 weeks. Full corrective therapy takes 2–3 months." },
      { q: "Is it NAFDAC approved?", a: "Yes. 100% NAFDAC approved. Registration number is printed on the product package." },
      { q: "Does it work if I have diabetes or high BP?", a: "Yes! One key advantage of Reodeo/Vigormax is that it works even if you have underlying conditions like diabetes or high blood pressure, unlike other alternatives." },
      { q: "How do I use this product?", a: "Once delivered, detailed instructions along with a special guide and food tips will be sent to you via WhatsApp or Email for optimal results." },
    ],
    testimonials: [
      { name: "Mr. Adeyemi K.", location: "Lagos", text: "After 2 years of embarrassment, I finally last over 40 minutes. My wife is amazed. This product saved my marriage.", rating: 5 },
      { name: "Chukwuemeka O.", location: "Enugu", text: "I was skeptical at first but after 3 weeks using the 3-bottle pack, I feel like I'm 25 again. Highly recommend!", rating: 5 },
      { name: "Musa A.", location: "Abuja", text: "Ordered the maxi pack. Best decision I ever made. Strong erection, lasting power — completely transformed.", rating: 5 },
    ],
  },
  {
    id: "prostate",
    slug: "prostate",
    name: "Prostate Health",
    tagline: "No More Painful, Frequent Urination",
    heroHeadline: "Treat Enlarged Prostate Permanently — No Surgery Required",
    heroSubheadline: "Reodeo + Prostbeta Pack — restore your prostate to its original healthy state naturally",
    productName: "Reodeo + Prostbeta Pack",
    whatsappKeyword: "Prostate",
    color: "blue",
    icon: "ShieldCheck",
    images: [
      "/images/products/prostate/prostate-1.png",
      "/images/products/prostate/prostate-2.png",
      "/images/products/prostate/prostate-3.png",
      "/images/products/prostate/prostate-4.png",
      "/images/products/prostate/prostate-5.png",
    ],
    educationalIntro: "Enlarged Prostate (BPH — Benign Prostatic Hyperplasia) is one of the most common health problems affecting men over 40 in Nigeria. It causes the prostate gland to swell and press against the urethra, leading to painful urination, weak urine stream, and frequent nighttime bathroom trips. Left untreated, it can lead to kidney damage, urinary tract infections, and even the need for surgery. But surgery is NOT your only option.",
    rootCauses: [
      "Age-related hormonal changes (common after 40)",
      "Chronic inflammation of the prostate",
      "Poor diet high in processed foods",
      "Sedentary lifestyle & obesity",
      "Untreated urinary tract infections",
      "Family history of prostate problems",
    ],
    howItWorks: "The REODEO + PROSTBETA Pack uses 25 natural phytoceutical extracts that work together to reduce prostate inflammation, restore normal prostate size, and strengthen the urinary system. It corrects the enlarged prostate gland and restores it to its original healthy state — meaning you will never have to wake up frequently at night to urinate again. The difficulty you experience when urinating will finally stop, and you will be able to fully empty your bladder at a go.",
    detailedBenefits: [
      { title: "Restores Prostate Health", description: "Corrects enlarged prostate and restores the gland to its original healthy state without surgery." },
      { title: "Ends Frequent Night Urination", description: "No more waking up 4–6 times a night. Enjoy peaceful, uninterrupted sleep again." },
      { title: "Restores Strong Urine Flow", description: "Eliminates weak stream, dribbling, and the inability to fully empty the bladder." },
      { title: "Improves Sexual Performance", description: "Also promotes stamina, libido, and supports firm erections — solving two problems at once." },
      { title: "Supports Testosterone & Hormones", description: "Balances healthy hormone levels, supports testosterone production, and fights free radicals." },
      { title: "Prevents Complications", description: "Treats blood in urine, prevents kidney damage, and heals urinary tract infections caused by BPH." },
    ],
    warningNote: "If you're already experiencing blood in urine or urinary tract infections due to an enlarged prostate, this pack will also help treat those conditions successfully.",
    pricingPacks: [
      { label: "Mini Pack", bottles: 2, originalPrice: 57500, salePrice: 47500, description: "For early symptoms & prevention", includedProducts: ["1 Prosbeta", "1 Longzit"] },
      { label: "Medium Pack", bottles: 3, originalPrice: 69500, salePrice: 59500, description: "Moderate prostate enlargement", recommended: true, includedProducts: ["2 Prosbeta", "1 Longzit", "1 Myco Balance"] },
      { label: "Maxi Pack", bottles: 4, originalPrice: 92500, salePrice: 82500, description: "Advanced treatment course", includedProducts: ["2 Prosbeta", "1 Longzit", "1 Myco Balance"] },
      { label: "Severe Pack", bottles: 5, originalPrice: 130000, salePrice: 120000, description: "Long-term or severe prostate conditions", includedProducts: ["3 Prosbeta", "1 Myco Balance", "1 Zinc"] },
    ],
    symptoms: [
      "Increased & frequent urination (especially at night)",
      "Pain while urinating",
      "Weak and interrupted urine stream",
      "Inability to empty the bladder during urination",
      "Difficulty in starting urination",
      "Dribbling after urination",
      "Blood in the urine",
      "Sexual performance decline",
    ],
    benefits: [
      "Stops frequent urination permanently",
      "Ends painful urination",
      "Restores strong urine flow",
      "Promotes stamina & libido",
      "Improves blood flow for firm erections",
      "Helps against premature release",
      "Supports immune system against infections",
      "Supports testosterone production",
      "Supports healthy hormone levels",
      "Eradicates ache after sex",
      "No surgery required",
      "NAFDAC approved",
    ],
    faqs: [
      { q: "What is BPH (enlarged prostate)?", a: "BPH is a non-cancerous enlargement of the prostate gland that blocks urine flow and causes pain. Very common in men over 40." },
      { q: "Does the product work?", a: "Yes! Over 1,509 people have used and testified about this product across African countries with a 100% success rate." },
      { q: "How many packs do I need?", a: "Normally 2 bottles should be okay, but we advise 4 bottles if the issue is critical. That's why we give a huge discount on larger packs." },
      { q: "Does it have side effects?", a: "No! It's a magic blend of 100% pure herbal product and plant extract to enhance libido and prostate health with no chemicals." },
      { q: "Does it help with erectile issues too?", a: "Yes! It addresses both prostate and sexual performance issues simultaneously — 100% effective." },
      { q: "How do I use this product?", a: "Once delivered, the instruction with a special guide and food tips will be sent to you via Text, WhatsApp, or Email." },
      { q: "Can I use it with my current drugs?", a: "No! Use it alone to see the full effectiveness of the treatment." },
    ],
    testimonials: [
      { name: "Chief Okonkwo E.", location: "Anambra", text: "I was waking up 6 times a night to urinate. After 3 bottles, I sleep through the night. God bless this product.", rating: 5 },
      { name: "Alhaji Bello M.", location: "Kano", text: "Doctors said I needed surgery. I refused and tried this natural approach. My prostate scan is now normal after 3 months.", rating: 5 },
      { name: "Pastor Taiwo A.", location: "Ibadan", text: "The dribbling and weak stream are gone. I feel younger and my confidence is back. Truly recommended.", rating: 5 },
    ],
  },
  {
    id: "diabetes",
    slug: "diabetes",
    name: "Diabetes Control",
    tagline: "Normalize Blood Sugar — No Lifelong Drugs",
    heroHeadline: "How to Normalize Your Blood Sugar Naturally Without Long-Term Medications",
    heroSubheadline: "NMN Capsules — science-backed blood sugar normalization for Type 1 & Type 2 diabetes",
    productName: "NMN Diabetes Capsules",
    whatsappKeyword: "Diabetes",
    color: "orange",
    icon: "Droplet",
    images: [
      "/images/products/diabetes/diabetes-1.png",
      "/images/products/diabetes/diabetes-2.png",
      "/images/products/diabetes/diabetes-3.png",
      "/images/products/diabetes/diabetes-4.png",
    ],
    educationalIntro: "Diabetes is a chronic, often debilitating and sometimes fatal disease where the body either cannot produce insulin or cannot properly use the insulin it produces. Insulin controls the amount of glucose (sugar) in the blood. When blood sugar rises beyond normal, it can damage blood vessels, organs, and nerves — silently destroying your health even when you don't feel sick. Blood vessels are to the body what fuel hoses are to a vehicle. Imagine them being damaged.",
    rootCauses: [
      "Insufficient insulin production by the pancreas",
      "Body's inability to properly use insulin (insulin resistance)",
      "Poor diet high in carbohydrates & sugar",
      "Genetic predisposition & family history",
      "Obesity & sedentary lifestyle",
      "Chronic stress & hormonal imbalances",
    ],
    howItWorks: "When we consume carbohydrates, they are broken down into glucose — the form of energy the body recognizes. For glucose to transfer from the blood into cells, insulin is needed. The pancreas produces this insulin through beta cells. When this process is disrupted and insulin production becomes insufficient, diabetes develops. NMN Capsules work by supporting pancreatic function, improving insulin sensitivity, and helping the body regulate blood sugar naturally — without the side effects of long-term pharmaceutical medications.",
    detailedBenefits: [
      { title: "Normalizes Blood Sugar", description: "Brings blood sugar levels back to safe, healthy ranges for both Type 1 and Type 2 diabetes." },
      { title: "Reduces Insulin Dependency", description: "Many patients report being able to reduce or stop their insulin/metformin medication under doctor supervision." },
      { title: "Improves Pancreatic Function", description: "Supports the beta cells in the pancreas to produce insulin more effectively." },
      { title: "Prevents Diabetic Complications", description: "Reduces risk of nerve damage, kidney disease, vision problems, and slow-healing wounds." },
      { title: "No Side Effects", description: "99% pure herbal formula with no chemicals. Safe for long-term use with persistent monitoring." },
      { title: "Proven Results", description: "Over 1,509 people have used and testified about this product with a 99% success rate." },
    ],
    warningNote: "Diabetes can be very deceptive — you may not feel sick as blood sugar rises, but rising levels can damage blood vessels in no time. Don't wait until complications arise.",
    pricingPacks: [
      { label: "Mini Pack", bottles: 3, originalPrice: 64500, salePrice: 54500, description: "2-month supply for mild diabetes", includedProducts: ["1 Dialese", "1 Longzit", "1 Royal Jelly"] },
      { label: "Medium Pack", bottles: 4, originalPrice: 78470, salePrice: 68470, description: "Best for Type 2 management", recommended: true, includedProducts: ["2 Dialese", "1 Longzit", "1 Royal Jelly"] },
      { label: "Max Pack", bottles: 6, originalPrice: 102500, salePrice: 92500, description: "For serious blood sugar issues", includedProducts: ["3 Dialese", "2 Royal Jelly", "1 Longzit"] },
      { label: "Severe Pack", bottles: 8, originalPrice: 130940, salePrice: 120940, description: "Long-term diabetes reversal program", includedProducts: ["4 Dialese", "2 Royal Jelly", "2 Longzit"] },
    ],
    symptoms: [
      "Consistently high blood sugar levels",
      "Excessive thirst & frequent urination",
      "Slow-healing wounds & cuts",
      "Extreme fatigue & low energy",
      "Sexual dysfunction & low libido",
      "Blurred vision",
      "Tingling or numbness in hands/feet",
      "Unexplained weight loss",
    ],
    benefits: [
      "Normalizes blood sugar levels",
      "Reduces insulin dependency",
      "Improves pancreatic function",
      "Reduces diabetic complications",
      "99% pure herbal formula",
      "Works for Type 1 & Type 2",
      "NAFDAC & FDA approved",
      "Tested on 1,509+ patients",
    ],
    faqs: [
      { q: "Does this product actually work?", a: "Yes! NMN Capsules have a 99% success rate. Over 1,509 people have used and testified about this product." },
      { q: "How many packs do I need?", a: "Normally one pack should be okay, but for critical or long-term cases we advise 2 or 3 months packs. That's why we give discounts on larger orders." },
      { q: "Does it have any side effects?", a: "No! This is a magic blend of 99% pure herbal product and plant extract to lower blood sugar. It has no chemicals in it." },
      { q: "Does it actually reverse diabetes?", a: "Yes! It effectively normalizes blood sugar in 99% of cases. Type 2 reversal is well-documented with natural approaches." },
      { q: "How do I use this product?", a: "Once delivered, the instruction with a special guide and food tips will be sent to you via WhatsApp, Email, or Text with persistent monitoring over phone." },
      { q: "Can I use it with my current drugs?", a: "No! Use it alone to see the effectiveness. Consult your doctor before stopping any prescribed medications." },
      { q: "Is this NAFDAC and FDA approved?", a: "100% approved. Registration number is printed on the product package." },
    ],
    testimonials: [
      { name: "Mrs. Nkechi A.", location: "Port Harcourt", text: "My sugar was at 350mg/dL. After 2 months, it's at 95. My doctor was shocked. I'm off metformin!", rating: 5 },
      { name: "Mr. Sule Y.", location: "Kaduna", text: "Type 2 diabetic for 8 years. Used the 3-bottle pack. Blood sugar normalized in 6 weeks. This is a miracle.", rating: 5 },
      { name: "Funmilayo O.", location: "Ogun", text: "My wounds were never healing. Since starting this treatment, everything is better. My energy is back!", rating: 5 },
    ],
  },
  {
    id: "infection",
    slug: "infection",
    name: "Infection Relief",
    tagline: "End Chronic Infections Permanently",
    heroHeadline: "The Ancient Way to Permanently Get Rid of Chronic Infections",
    heroSubheadline: "Say goodbye to drug-resistant infections — 100% herbal, 99.9% bacteria & virus killing rate",
    productName: "Herbal Infection Relief Pack",
    whatsappKeyword: "Infection Relief",
    color: "teal",
    icon: "ShieldAlert",
    images: [
      "/images/products/infection/infection-1.png",
      "/images/products/infection/infection-2.png",
      "/images/products/infection/infection-3.png",
      "/images/products/infection/infection-4.png",
      "/images/products/infection/infection-5.png",
    ],
    educationalIntro: "Stop wasting money on antibiotics that don't work. Most infections keep coming back because you're treating them the wrong way. Many people struggle with infections that never fully go away, no matter how many times they're treated. That's because not all infections are caused by bacteria — and antibiotics only work on bacterial infections. Years of self-medication, overuse, and abuse of antibiotics have led to drug-resistant infections that no longer respond to conventional treatments.",
    rootCauses: [
      "Antibiotic resistance from years of overuse",
      "Self-medication & wrong treatment approach",
      "Treating viral infections with antibiotics (ineffective)",
      "Weakened immune system",
      "Unprotected sexual contact",
      "Poor hygiene & sanitation conditions",
      "Incomplete treatment courses",
    ],
    howItWorks: "Our Herbal Infection Relief Pack uses a combination of potent natural antimicrobials that kill bacteria, viruses, fungi, and parasites at a 99.9% rate — including drug-resistant strains that antibiotics cannot touch. The pack includes ingredients that cleanse blood waste, treat visceral viruses, and work as natural antibiotics that inhibit and kill many kinds of germs. It also relieves inflammation in the gynaecological and urinary systems while supporting overall immune function.",
    detailedBenefits: [
      { title: "Kills 99.9% of Pathogens", description: "Effective against drug-resistant staphylococcus aureus, gonorrhea, syphilis, candida albicans, and genital herpes." },
      { title: "Cleanses Blood Waste", description: "Eliminates blood impurities and treats conditions caused by visceral viruses lodged deep in the system." },
      { title: "Treats Gynaecological Issues", description: "Effective for vaginal inflammation, genital itching, PID, and other reproductive system infections." },
      { title: "Heals Urinary Infections", description: "Treats UTIs, reduces frequent urination, and eliminates burning sensations during urination." },
      { title: "Boosts Immunity & Detoxes", description: "Destroys bad bacteria while protecting good gut bacteria. Detoxifies heavy metals from the body." },
      { title: "Promotes Overall Healing", description: "Supports wound tissue recovery, improves skin health, and reduces cholesterol levels." },
    ],
    warningNote: "If antibiotics have failed you repeatedly, it's likely because you've been using the wrong treatment. Our herbal formula targets the infections that conventional medicine cannot touch.",
    pricingPacks: [
      { label: "Mini Pack", bottles: 4, originalPrice: 79500, salePrice: 69500, description: "For mild/recent infections", includedProducts: ["1 Garlic Oil", "2 Ganoderma", "1 B-Clear"] },
      { label: "Medium Pack", bottles: 5, originalPrice: 104410, salePrice: 94410, description: "For recurring infections", recommended: true, includedProducts: ["1 Garlic Oil", "2 Ganoderma", "1 B-Clear", "1 Micro Balance"] },
      { label: "Severe Pack", bottles: 7, originalPrice: 130960, salePrice: 120960, description: "For severe or long-term chronic infections", includedProducts: ["2 Garlic Oil", "2 Ganoderma", "2 B-Clear", "1 Micro Balance"] },
    ],
    symptoms: [
      "Painful & smelly discharge",
      "Staphylococcus aureus infection",
      "Gonorrhea & Chlamydia",
      "Genital herpes & HPV",
      "STDs, PID & genital warts",
      "E-Coli infections",
      "Vaginal/penile discharge",
      "Pain during sex",
      "Frequent urination & burning",
      "Weak erection from infection",
      "Low sperm count & watery sperm",
    ],
    benefits: [
      "Kills 99.9% of bacteria & viruses",
      "Clears Staph, Gonorrhea, Herpes, Syphilis",
      "Treats gynaecological inflammation",
      "Relieves vaginal/genital itching",
      "Improves sperm quality",
      "Heals urinary tract infections",
      "Cleanses blood waste & detoxifies",
      "Boosts immunity & gut health",
      "Improves skin health",
      "100% natural antibiotics",
      "NAFDAC approved",
    ],
    faqs: [
      { q: "Why don't antibiotics work for me?", a: "Years of overuse and self-medication have made most bacteria antibiotic-resistant. Our herbal formula targets resistant strains that regular antibiotics can't kill." },
      { q: "Can it treat STDs?", a: "Yes. It's effective against gonorrhea, syphilis, chlamydia, herpes, HPV, E-Coli, and other STDs with a 99.9% killing rate." },
      { q: "How many bottles do I need?", a: "Mild/recent cases: 3 bottles. Recurring/moderate: 4 bottles. Severe/long-term: 5 bottles." },
      { q: "Is it safe for both men and women?", a: "Yes. The formula is designed for both male and female reproductive health conditions." },
      { q: "Does it have side effects?", a: "No side effects. 100% pure herbal extracts with natural antimicrobial properties." },
      { q: "Will the infection come back?", a: "Unlike antibiotics, our herbal formula provides a permanent cure by eliminating the infection at its root, not just suppressing symptoms." },
    ],
    testimonials: [
      { name: "Anonymous (F)", location: "Lagos", text: "I had discharge and Staph for 2 years. Tried every antibiotic. 3 bottles of this and I'm 100% clear. I cried with joy.", rating: 5 },
      { name: "Emeka T.", location: "Benin", text: "Gonorrhea that kept returning. Finally gone after the medium pack. My test came back negative. Incredible.", rating: 5 },
      { name: "Yetunde A.", location: "Abeokuta", text: "UTI kept coming back. This fixed it permanently. No more burning or pain. Life is good again!", rating: 5 },
    ],
  },
  {
    id: "joint-pain",
    slug: "joint-pain",
    name: "Joint Pain & Arthritis",
    tagline: "Move Freely, Live Without Pain",
    heroHeadline: "Natural Solutions to End Any Form of Joint Pain & Arthritis",
    heroSubheadline: "100% herbal joint relief — no painkillers, no surgery, no side effects",
    productName: "Joint & Arthritis Relief Pack",
    whatsappKeyword: "JOINT AND ARTHRITIS",
    color: "purple",
    icon: "Bone",
    images: [
      "/images/products/joint-pain/joint-1.png",
      "/images/products/joint-pain/joint-2.png",
      "/images/products/joint-pain/joint-3.png",
    ],
    educationalIntro: "If you're tired of the constant pain, stiffness, and discomfort — and you're searching for a natural, safe, and fast-working solution with zero side effects — then this could be the most important message you'll come across today. Life can be very unbearable and frustrating when you cannot carry out your daily activities without feeling pain. Whether it's climbing stairs, walking to the gate, or simply getting out of bed — joint pain, arthritis, and rheumatism can turn the simplest tasks into punishment.",
    rootCauses: [
      "Age-related cartilage deterioration",
      "Autoimmune disorders (rheumatoid arthritis)",
      "Previous injury or joint trauma",
      "Obesity & excess weight on joints",
      "Chronic inflammation",
      "Poor blood circulation to joints",
      "Calcium & mineral deficiency",
    ],
    howItWorks: "Our Joint & Arthritis Relief Pack is a well-researched herbal remedy that works by reducing inflammation in the joint tissues, promoting blood circulation to affected areas, and supporting the body's natural healing processes. It relieves pain fast while addressing the root causes — not just masking symptoms like painkillers do. The formula also helps build strong bones, stabilize blood pressure, and contributes to normal cardiovascular function.",
    detailedBenefits: [
      { title: "Fast Pain Relief", description: "Relieves joint pain, bone pain, and general body aches naturally without dependency on painkillers." },
      { title: "Reduces Swelling & Stiffness", description: "Targets inflammation at the source, reducing swelling and restoring comfortable movement." },
      { title: "Restores Mobility & Flexibility", description: "Helps you walk, climb stairs, and perform daily activities without fear or discomfort." },
      { title: "Treats Rheumatoid Arthritis", description: "Effective for all forms of rheumatism, cervical spondylitis, and lumbar muscle strain." },
      { title: "Builds Stronger Bones", description: "Supports calcium absorption, prevents osteoporosis, and reduces the incidence of bone disease." },
      { title: "Improves Cardiovascular Health", description: "Stabilizes blood pressure, supports muscle movement, and contributes to normal heart function." },
    ],
    warningNote: "Over 245,509 people have used and testified about this product. Relief is real — and it's possible. Don't give up.",
    pricingPacks: [
      { label: "Mini Pack", bottles: 2, originalPrice: 49500, salePrice: 39500, description: "For early-stage joint stiffness", includedProducts: ["1 Panicept", "1 Spabucta Spray"] },
      { label: "Medium Pack", bottles: 3, originalPrice: 66500, salePrice: 56500, description: "For moderate arthritis pain", recommended: true, includedProducts: ["1 Panicept", "1 Spabucta Spray", "1 Longzit"] },
      { label: "Severe Pack", bottles: 8, originalPrice: 130540, salePrice: 120540, description: "For chronic, long-term joint conditions", includedProducts: ["3 Panicept", "2 Spabucta Spray", "2 Longzit", "1 Hi Calcium"] },
    ],
    symptoms: [
      "Constant joint pain that won't go away",
      "Morning stiffness lasting hours",
      "Swollen, tender joints",
      "Cannot climb stairs without holding the rail",
      "Pain that wakes you at night",
      "Limited movement & flexibility loss",
      "Knee, hip, back, or shoulder pain",
      "Dependence on painkillers with no lasting relief",
    ],
    benefits: [
      "Relieves joint pain fast & naturally",
      "Reduces swelling & inflammation",
      "Restores flexibility & mobility",
      "Effective for rheumatoid arthritis",
      "Relieves cervical spondylitis",
      "Helps lumbar muscle strain & bone pains",
      "Promotes blood circulation",
      "Builds strong bones & teeth",
      "Helps prevent osteoporosis",
      "Stabilizes blood pressure",
      "NAFDAC & FDA approved",
    ],
    faqs: [
      { q: "Does the product work?", a: "Yes! It works 100%. Over 245,509 people have used and testified about this product." },
      { q: "Does it have any side effects?", a: "No! It's a magic blend of 100% pure herbal product and plant extract. It has no chemicals in it." },
      { q: "How many packs do I need?", a: "Normally one pack should be okay. But for critical issues, we advise 2 or 3 months packs. That's why we give huge discounts on larger orders." },
      { q: "Does it finally reverse joint/arthritis issues?", a: "Yes! It's done 100%. The formula addresses root causes, not just symptoms." },
      { q: "How do I use this product?", a: "Once delivered, the instruction with a special guide and food tips will be sent to you via WhatsApp or Email." },
      { q: "Can I use it with my current drugs?", a: "No! Use it alone to see the effectiveness." },
      { q: "Is this NAFDAC and FDA approved?", a: "100% approved. Registration number is printed on the product package." },
    ],
    testimonials: [
      { name: "Mama Chisom", location: "Owerri", text: "I couldn't walk to the kitchen without crying from pain. After 6 weeks, I danced at my granddaughter's naming ceremony. Thank you!", rating: 5 },
      { name: "Alhaji Danjuma", location: "Sokoto", text: "Knee pain for 7 years. Doctors said I needed replacement surgery. This product saved me from that. I walk freely now.", rating: 5 },
      { name: "Mrs. Adaeze N.", location: "Onitsha", text: "My rheumatoid arthritis was destroying my hands. After 3 months, I can hold a cup without pain. Incredible results.", rating: 5 },
    ],
  },
  {
    id: "blood-pressure",
    slug: "blood-pressure",
    name: "Blood Pressure",
    tagline: "Steady Pressure. Steady Life.",
    heroHeadline: "Take Control of Your Blood Pressure Naturally",
    heroSubheadline: "GHT BP Support + GHT Caerite — steady blood-pressure control + targeted heart protection",
    productName: "HBP Solution Pack",
    whatsappKeyword: "BP TREATMENT",
    color: "red",
    icon: "Heart",
    images: [
      "/images/products/blood-pressure/blood-pressure-1.png",
      "/images/products/blood-pressure/blood-pressure-2.png",
      "/images/products/blood-pressure/blood-pressure-3.png",
      "/images/products/blood-pressure/blood-pressure-4.png",
    ],
    educationalIntro: "High blood pressure, often called the \"Silent Killer,\" affects millions of people without warning. Many don't even know they have it until it becomes life-threatening — causing strokes, heart attacks, kidney failure, and blindness. The good news is that lowering your blood pressure naturally is not only possible — it's simpler than you might think. With the right natural approach, you can protect your heart and restore your health.",
    rootCauses: [
      "Poor diet high in salt & processed foods",
      "Chronic stress & anxiety",
      "Obesity & lack of physical activity",
      "Excessive alcohol consumption",
      "Smoking & tobacco use",
      "Genetic predisposition & family history",
      "Underlying kidney or hormonal issues",
    ],
    howItWorks: "GHT BP Support + GHT Caerite provides steady blood-pressure control and targeted heart protection in one carefully packaged kit. The HBP Solution Pack is made up of strictly natural ingredients with no negative side effects. It carries prestigious certifications including the Kosher Seal (accepted by Jews who don't take anything that isn't 100% natural), Halal and Islamic seals, International Aloe Science Council certification, and Nigeria's own NAFDAC approval.",
    detailedBenefits: [
      { title: "Maintains Healthy Blood Pressure", description: "Supports stable readings and helps your body maintain healthy blood pressure levels naturally." },
      { title: "Improves Heart Circulation", description: "Enhances healthy blood flow to all organs, reducing strain on the cardiovascular system." },
      { title: "Reduces Symptoms", description: "Eliminates headaches, dizziness, chest tightness, and heart palpitations associated with hypertension." },
      { title: "Supports Heart Muscle Health", description: "Strengthens heart muscle, manages cholesterol levels, and improves cardiac output." },
      { title: "Boosts Energy & Sleep", description: "Customers report improved energy levels during the day and significantly better sleep quality at night." },
      { title: "Internationally Certified", description: "Carries Kosher, Halal, International Aloe Science Council, and NAFDAC seals — the highest form of purity assurance." },
    ],
    warningNote: "High blood pressure is called the 'Silent Killer' because you may not feel its effects until it's too late. Don't wait for a stroke or heart attack to take action.",
    pricingPacks: [
      { label: "Mini Pack", bottles: 4, originalPrice: 87500, salePrice: 77500, description: "For borderline high blood pressure", includedProducts: ["1 HyperFree Tablet", "1 Caerite", "1 Royal Jelly", "1 I-Detox Tea"] },
      { label: "Medium Pack", bottles: 7, originalPrice: 150500, salePrice: 140500, description: "For consistent hypertension", recommended: true, includedProducts: ["2 HyperFree Tablet", "1 Caerite", "3 Royal Jelly", "1 I-Detox Tea"] },
    ],
    symptoms: [
      "Consistently high blood pressure readings",
      "Frequent & severe headaches",
      "Dizziness & blurred vision",
      "Chest tightness & heart palpitations",
      "Shortness of breath during normal activities",
      "Nose bleeds",
      "Poor sleep quality & restlessness",
      "Fatigue & low energy",
    ],
    benefits: [
      "Normalizes blood pressure readings",
      "Improves blood circulation to organs",
      "Reduces headaches & dizziness",
      "Supports heart muscle health",
      "Manages cholesterol naturally",
      "Boosts energy & sleep quality",
      "Detoxifies body systems",
      "Kosher, Halal & NAFDAC certified",
      "Safe for long-term use",
    ],
    faqs: [
      { q: "Can I stop my blood pressure medication?", a: "Don't stop abruptly. Many customers gradually reduce medication as BP normalizes. Always consult your doctor." },
      { q: "How long until my BP normalizes?", a: "Most customers see improvement within 3–4 weeks. For stable long-term control, use for 2–3 months." },
      { q: "Is it safe with heart conditions?", a: "Yes. It's formulated to support heart health. However, inform your cardiologist if you have a diagnosed heart condition." },
      { q: "What certifications does this have?", a: "Kosher seal, Halal seal, International Aloe Science Council, and NAFDAC Nigeria registration — seals of the highest form of purity." },
      { q: "Does it work for both systolic and diastolic hypertension?", a: "Yes. It helps normalize both numbers and improves overall cardiovascular health." },
      { q: "How do I use this product?", a: "Once delivered, you'll receive a detailed instruction guide with usage directions, food tips, and lifestyle support sent directly via WhatsApp." },
      { q: "Can I use it with my current medications?", a: "For best results, we recommend using the pack alone. If on prescribed drugs, kindly consult your doctor before use." },
    ],
    testimonials: [
      { name: "Bro. Festus O.", location: "Delta", text: "BP was 180/110 for 3 years. After 2 months on this pack, I'm at 128/82. My doctor is monitoring me to reduce my medication.", rating: 5 },
      { name: "Mrs. Zainab I.", location: "Katsina", text: "I had constant headaches from hypertension. They stopped in the second week. This product is a lifesaver.", rating: 5 },
      { name: "Mr. Anthony O.", location: "Cross River", text: "Both my wife and I use the BP pack. We've maintained healthy readings for 6 months now without side effects.", rating: 5 },
    ],
  },
  {
    id: "ulcer",
    slug: "ulcer",
    name: "Ulcer Relief",
    tagline: "Natural Healing for Gastric Health",
    heroHeadline: "Permanent Relief from Stomach Ulcers Naturally",
    heroSubheadline: "100% herbal Ulcer Relief Pack — eliminates pain, heals the stomach lining, and prevents recurrence",
    productName: "Ulcer Care Pack",
    whatsappKeyword: "ULCER TREATMENT",
    color: "emerald",
    icon: "Leaf",
    images: [
      "/images/products/ulcer/ulcer-1.png",
      "/images/products/ulcer/ulcer-2.png",
    ],
    educationalIntro: "Stomach ulcers are painful sores in the stomach lining that can make eating and daily life a nightmare. Often caused by H. pylori bacteria or long-term use of anti-inflammatory drugs, ulcers can lead to severe complications if left untreated. Our natural approach focuses on eliminating the root cause and promoting the regeneration of the stomach lining.",
    rootCauses: [
      "H. pylori bacterial infection",
      "Long-term use of NSAIDs (painkillers)",
      "Excessive stomach acid production",
      "Chronic stress & poor diet",
      "Smoking & alcohol consumption",
    ],
    howItWorks: "The Ulcer Care Pack works by neutralizing excess acid, coating the stomach lining to protect it from further irritation, and using potent herbal extracts to kill H. pylori bacteria. It stimulates the body's natural healing process to repair the damaged tissues, providing permanent relief without the side effects of conventional antacids.",
    detailedBenefits: [
      { title: "Heals Stomach Lining", description: "Promotes the regeneration of healthy tissue in the stomach and intestinal lining." },
      { title: "Eliminates H. Pylori", description: "Natural antimicrobial properties target and kill the bacteria responsible for most ulcers." },
      { title: "Fast Pain Relief", description: "Quickly soothes burning sensations and abdominal pain associated with ulcers." },
      { title: "Prevents Recurrence", description: "Strengthens the stomach's natural defenses to prevent ulcers from returning." },
    ],
    pricingPacks: [
      { label: "Mini Pack", bottles: 2, originalPrice: 59500, salePrice: 49500, description: "For mild or recent ulcer symptoms", includedProducts: ["1 Sto-Care", "1 Garlic Oil"] },
      { label: "Medium Pack", bottles: 4, originalPrice: 89500, salePrice: 79500, description: "Complete healing course", recommended: true, includedProducts: ["2 Sto-Care", "2 Garlic Oil"] },
      { label: "Severe Pack", bottles: 4, originalPrice: 115570, salePrice: 105570, description: "For chronic or long-term ulcers", includedProducts: ["3 Sto-Care", "1 Garlic Oil"] },
    ],
    symptoms: [
      "Burning stomach pain",
      "Frequent bloating and burping",
      "Nausea or vomiting",
      "Heartburn or acid reflux",
      "Loss of appetite & weight loss",
    ],
    benefits: [
      "Permanent relief from ulcer pain",
      "Heals stomach & duodenal ulcers",
      "Eliminates H. pylori naturally",
      "Improves digestion & nutrient absorption",
      "100% herbal — safe and effective",
    ],
    faqs: [
      { q: "How long before I see results?", a: "Most users feel significant relief from pain within 7-14 days. Complete healing typically takes 1-2 months." },
      { q: "Does it work for chronic ulcers?", a: "Yes, our formula is specifically designed to address long-standing and recurring ulcer conditions." },
      { q: "Can I use it with antacids?", a: "Our formula is self-sufficient, but you can consult your doctor if you're currently taking other medications." },
    ],
    testimonials: [
      { name: "John D.", location: "Lagos", text: "I struggled with ulcers for 5 years. This pack changed my life. No more pain!", rating: 5 },
      { name: "Sarah O.", location: "Ibadan", text: "Truly effective. I can now eat spicy food again without any issues. Thank you!", rating: 5 },
    ],
  },
];

export const getProductBySlug = (slug: string): Product | undefined =>
  products.find((p) => p.slug === slug);
