export const WHATSAPP_NUMBER = "2348140874503";

export function getWhatsAppLink(productName: string): string {
  const message = `Hello Dr I've Read And I Want To Place Order For Your ${productName} Treatment Pack!`;
  return `https://api.whatsapp.com/send?phone=${WHATSAPP_NUMBER}&text=${encodeURIComponent(message)}`;
}

export interface PricingPack {
  label: string;
  bottles: number;
  originalPrice: number;
  salePrice: number;
  description: string;
  recommended?: boolean;
  includedProducts?: string[];
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  heroHeadline: string;
  heroSubheadline: string;
  productName: string;
  whatsappKeyword: string;
  color: string;
  icon: string;
  images: string[];
  pricingPacks: PricingPack[];
  symptoms: string[];
  benefits: string[];
  faqs: { q: string; a: string }[];
  testimonials: { name: string; location: string; text: string; rating: number }[];
  // New enriched content fields
  educationalIntro?: string;
  rootCauses?: string[];
  howItWorks?: string;
  detailedBenefits?: { title: string; description: string }[];
  warningNote?: string;
}

export const products: Product[] = [
  {
    id: "ed",
    slug: "ed-sexual-health",
    name: "ED & Sexual Health",
    tagline: "Rock-Hard Performance, Naturally",
    heroHeadline: "End Erectile Dysfunction & Last Over 50 Minutes In Bed",
    heroSubheadline: "Reodeo/Vigormax Capsules — 100% herbal, NAFDAC approved, zero side effects",
    productName: "Reodeo/Vigormax Capsules",
    whatsappKeyword: "WEAK ERECTION",
    color: "rose",
    icon: "Activity",
    images: [
      "/images/products/ed/ed-1.png",
      "/images/products/ed/ed-2.png",
    ],
    educationalIntro: "Erectile Dysfunction (ED) is a condition that crushes the confidence, ego, and happiness of a grown man — and it affects millions of Nigerian men across all age groups. Whether it's weak erections, premature ejaculation (finishing in under 1 minute), or complete loss of sexual desire, ED can silently destroy relationships and self-esteem. The good news? It doesn't have to be permanent.",
    rootCauses: [
      "Temporary depression & chronic stress",
      "Underlying infections (Staph, STDs)",
      "Prostatitis or prostate enlargement",
      "Heart disease & clogged blood vessels",
      "High cholesterol & high blood pressure",
      "Diabetes (Type 1 & Type 2)",
      "Obesity & poor nutrition",
      "Alcoholism & substance abuse",
      "Drug abuse (pharma-based pills like Viagra/Cialis)",
    ],
    howItWorks: "Reodeo/Vigormax Capsules is a naturally fortified solution that combines the power of ancient herbs to support optimum performance of the male sexual organ. It is non-hormonal and never addictive. Unlike pharmaceutical drugs like Viagra or Cialis that only provide temporary relief with dangerous side effects, this herbal formula performs a gradual corrective function — even if you have diabetes or high blood pressure. Over 6,000 men between ages 30 and 80 have used this product since 2013, all with documented success.",
    detailedBenefits: [
      { title: "Restores Strong Erections", description: "Permanently restores your ability to maintain rock-hard erections — not a temporary fix like pharma pills." },
      { title: "Ends Premature Ejaculation", description: "Go from finishing in under 1 minute to lasting 50+ minutes per round, naturally and consistently." },
      { title: "Boosts Sperm Count & Libido", description: "Enhances male libido, increases sperm production, and supports healthy testosterone levels." },
      { title: "Works With Underlying Conditions", description: "Unlike other solutions, it works even if you have diabetes, high blood pressure, or high cholesterol." },
      { title: "Supports Prostate Health", description: "Also helps with prostate symptoms like frequent urination, supporting overall male reproductive health." },
      { title: "Zero Side Effects", description: "100% pure herbal blend — no chemicals, no addiction, no dependency. Safe for long-term use." },
    ],
    warningNote: "This product is designed for men who are ready to make permanent changes to their sexual health. It is a corrective therapy, not a one-time stimulant.",
    pricingPacks: [
      { label: "Treatment Pack", bottles: 2, originalPrice: 53500, salePrice: 43500, description: "Reodeo & Vigo Max — ED treatment", recommended: true, includedProducts: ["1 Reodeo", "1 Vigo Max"] },
    ],
    symptoms: [
      "Weak or no erection at all",
      "Premature ejaculation (finishing under 1 minute)",
      "Complete loss of interest in sex",
      "Unable to maintain erection during foreplay",
      "Erection drops immediately after penetration",
      "Cannot achieve a second round for 24+ hours",
      "Partner dissatisfaction & relationship strain",
      "Low confidence & anxiety in the bedroom",
    ],
    benefits: [
      "Rock-hard erections restored permanently",
      "Lasts 50+ minutes per round",
      "Boosts sperm count & libido",
      "Ends premature ejaculation",
      "100% herbal — no side effects",
      "Works even with diabetes or hypertension",
      "Non-addictive, no pharma chemicals",
      "Improved testosterone levels",
      "Supports immune system",
      "Promotes vitality & endurance",
    ],
    faqs: [
      { q: "Does this product really work?", a: "Yes! Over 6,000 men have used it since 2013 with documented success. It has been personally prescribed by health practitioners to men between ages 30–80 with consistent positive results." },
      { q: "How many bottles do I need?", a: "2 bottles is a good start for mild cases. For permanent results and severe conditions, we recommend 3–5 bottles depending on severity." },
      { q: "Does it have side effects?", a: "No. It's a 100% pure herbal blend with no chemicals, no additives, and no dependency. It's completely safe for long-term use." },
      { q: "Can I use it with my current medications?", a: "We recommend using it alone to see full effectiveness. Consult your doctor if currently on prescription drugs." },
      { q: "How long before I see results?", a: "Most customers notice significant changes within the first 2–3 weeks. Full corrective therapy takes 2–3 months." },
      { q: "Is it NAFDAC approved?", a: "Yes. 100% NAFDAC approved. Registration number is printed on the product package." },
      { q: "Does it work if I have diabetes or high BP?", a: "Yes! One key advantage of Reodeo/Vigormax is that it works even if you have underlying conditions like diabetes or high blood pressure, unlike other alternatives." },
      { q: "How do I use this product?", a: "Once delivered, detailed instructions along with a special guide and food tips will be sent to you via WhatsApp or Email for optimal results." },
    ],
    testimonials: [
      { name: "Mr. Adeyemi K.", location: "Lagos", text: "After 2 years of embarrassment, I finally last over 40 minutes. My wife is amazed. This product saved my marriage.", rating: 5 },
      { name: "Chukwuemeka O.", location: "Enugu", text: "I was skeptical at first but after 3 weeks using the 3-bottle pack, I feel like I'm 25 again. Highly recommend!", rating: 5 },
      { name: "Musa A.", location: "Abuja", text: "Ordered the maxi pack. Best decision I ever made. Strong erection, lasting power — completely transformed.", rating: 5 },
    ],
  },
  {
    id: "prostate",
    slug: "prostate",
    name: "Prostate Health",
    tagline: "No More Painful, Frequent Urination",
    heroHeadline: "Treat Enlarged Prostate Permanently — No Surgery Required",
    heroSubheadline: "Reodeo + Prostbeta Pack — restore your prostate to its original healthy state naturally",
    productName: "Reodeo + Prostbeta Pack",
    whatsappKeyword: "Prostate",
    color: "blue",
    icon: "ShieldCheck",
    images: [
      "/product_images/PROSBETA.png",
      "/product_images/LONGZIT.png",
      "/product_images/VIDOR-MAX.png",
    ],
    educationalIntro: "Enlarged Prostate (BPH — Benign Prostatic Hyperplasia) is one of the most common health problems affecting men over 40 in Nigeria. It causes the prostate gland to swell and press against the urethra, leading to painful urination, weak urine stream, and frequent nighttime bathroom trips. Left untreated, it can lead to kidney damage, urinary tract infections, and even the need for surgery. But surgery is NOT your only option.",
    rootCauses: [
      "Age-related hormonal changes (common after 40)",
      "Chronic inflammation of the prostate",
      "Poor diet high in processed foods",
      "Sedentary lifestyle & obesity",
      "Untreated urinary tract infections",
      "Family history of prostate problems",
    ],
    howItWorks: "The REODEO + PROSTBETA Pack uses 25 natural phytoceutical extracts that work together to reduce prostate inflammation, restore normal prostate size, and strengthen the urinary system. It corrects the enlarged prostate gland and restores it to its original healthy state — meaning you will never have to wake up frequently at night to urinate again. The difficulty you experience when urinating will finally stop, and you will be able to fully empty your bladder at a go.",
    detailedBenefits: [
      { title: "Restores Prostate Health", description: "Corrects enlarged prostate and restores the gland to its original healthy state without surgery." },
      { title: "Ends Frequent Night Urination", description: "No more waking up 4–6 times a night. Enjoy peaceful, uninterrupted sleep again." },
      { title: "Restores Strong Urine Flow", description: "Eliminates weak stream, dribbling, and the inability to fully empty the bladder." },
      { title: "Improves Sexual Performance", description: "Also promotes stamina, libido, and supports firm erections — solving two problems at once." },
      { title: "Supports Testosterone & Hormones", description: "Balances healthy hormone levels, supports testosterone production, and fights free radicals." },
      { title: "Prevents Complications", description: "Treats blood in urine, prevents kidney damage, and heals urinary tract infections caused by BPH." },
    ],
    warningNote: "If you're already experiencing blood in urine or urinary tract infections due to an enlarged prostate, this pack will also help treat those conditions successfully.",
  pricingPacks: [
    { label: "Treatment Pack", bottles: 3, originalPrice: 85500, salePrice: 71600, description: "Prostbeta, Longzit & Vigor Max — complete prostate treatment", recommended: true, includedProducts: ["1 Prostbeta", "1 Longzit", "1 Vigor Max"] },
  ],
    symptoms: [
      "Increased & frequent urination (especially at night)",
      "Pain while urinating",
      "Weak and interrupted urine stream",
      "Inability to empty the bladder during urination",
      "Difficulty in starting urination",
      "Dribbling after urination",
      "Blood in the urine",
      "Sexual performance decline",
    ],
    benefits: [
      "Stops frequent urination permanently",
      "Ends painful urination",
      "Restores strong urine flow",
      "Promotes stamina & libido",
      "Improves blood flow for firm erections",
      "Helps against premature release",
      "Supports immune system against infections",
      "Supports testosterone production",
      "Supports healthy hormone levels",
      "Eradicates ache after sex",
      "No surgery required",
      "NAFDAC approved",
    ],
    faqs: [
      { q: "What is BPH (enlarged prostate)?", a: "BPH is a non-cancerous enlargement of the prostate gland that blocks urine flow and causes pain. Very common in men over 40." },
      { q: "Does the product work?", a: "Yes! Over 1,509 people have used and testified about this product across African countries with a 100% success rate." },
      { q: "How many packs do I need?", a: "Normally 2 bottles should be okay, but we advise 4 bottles if the issue is critical. That's why we give a huge discount on larger packs." },
      { q: "Does it have side effects?", a: "No! It's a magic blend of 100% pure herbal product and plant extract to enhance libido and prostate health with no chemicals." },
      { q: "Does it help with erectile issues too?", a: "Yes! It addresses both prostate and sexual performance issues simultaneously — 100% effective." },
      { q: "How do I use this product?", a: "Once delivered, the instruction with a special guide and food tips will be sent to you via Text, WhatsApp, or Email." },
      { q: "Can I use it with my current drugs?", a: "No! Use it alone to see the full effectiveness of the treatment." },
    ],
    testimonials: [
      { name: "Chief Okonkwo E.", location: "Anambra", text: "I was waking up 6 times a night to urinate. After 3 bottles, I sleep through the night. God bless this product.", rating: 5 },
      { name: "Alhaji Bello M.", location: "Kano", text: "Doctors said I needed surgery. I refused and tried this natural approach. My prostate scan is now normal after 3 months.", rating: 5 },
      { name: "Pastor Taiwo A.", location: "Ibadan", text: "The dribbling and weak stream are gone. I feel younger and my confidence is back. Truly recommended.", rating: 5 },
    ],
  },
  {
    id: "diabetes",
    slug: "diabetes",
    name: "Diabetes Control",
    tagline: "Normalize Blood Sugar — No Lifelong Drugs",
    heroHeadline: "How to Normalize Your Blood Sugar Naturally Without Long-Term Medications",
    heroSubheadline: "NMN Capsules — science-backed blood sugar normalization for Type 1 & Type 2 diabetes",
    productName: "NMN Diabetes Capsules",
    whatsappKeyword: "Diabetes",
    color: "orange",
    icon: "Droplet",
    images: [
      "/product_images/DIALESE.png",
      "/product_images/LONGZIT.png",
      "/product_images/MYCO-BALANCE.png",
    ],
    educationalIntro: "Diabetes is a chronic, often debilitating and sometimes fatal disease where the body either cannot produce insulin or cannot properly use the insulin it produces. Insulin controls the amount of glucose (sugar) in the blood. When blood sugar rises beyond normal, it can damage blood vessels, organs, and nerves — silently destroying your health even when you don't feel sick. Blood vessels are to the body what fuel hoses are to a vehicle. Imagine them being damaged.",
    rootCauses: [
      "Insufficient insulin production by the pancreas",
      "Body's inability to properly use insulin (insulin resistance)",
      "Poor diet high in carbohydrates & sugar",
      "Genetic predisposition & family history",
      "Obesity & sedentary lifestyle",
      "Chronic stress & hormonal imbalances",
    ],
    howItWorks: "When we consume carbohydrates, they are broken down into glucose — the form of energy the body recognizes. For glucose to transfer from the blood into cells, insulin is needed. The pancreas produces this insulin through beta cells. When this process is disrupted and insulin production becomes insufficient, diabetes develops. NMN Capsules work by supporting pancreatic function, improving insulin sensitivity, and helping the body regulate blood sugar naturally — without the side effects of long-term pharmaceutical medications.",
    detailedBenefits: [
      { title: "Normalizes Blood Sugar", description: "Brings blood sugar levels back to safe, healthy ranges for both Type 1 and Type 2 diabetes." },
      { title: "Reduces Insulin Dependency", description: "Many patients report being able to reduce or stop their insulin/metformin medication under doctor supervision." },
      { title: "Improves Pancreatic Function", description: "Supports the beta cells in the pancreas to produce insulin more effectively." },
      { title: "Prevents Diabetic Complications", description: "Reduces risk of nerve damage, kidney disease, vision problems, and slow-healing wounds." },
      { title: "No Side Effects", description: "99% pure herbal formula with no chemicals. Safe for long-term use with persistent monitoring." },
      { title: "Proven Results", description: "Over 1,509 people have used and testified about this product with a 99% success rate." },
    ],
    warningNote: "Diabetes can be very deceptive — you may not feel sick as blood sugar rises, but rising levels can damage blood vessels in no time. Don't wait until complications arise.",
  pricingPacks: [
    { label: "Treatment Pack", bottles: 3, originalPrice: 84000, salePrice: 69896, description: "Dialese, Longzit & Myco Balance — blood sugar normalization", recommended: true, includedProducts: ["1 Dialese", "1 Longzit", "1 Myco Balance"] },
  ],
    symptoms: [
      "Consistently high blood sugar levels",
      "Excessive thirst & frequent urination",
      "Slow-healing wounds & cuts",
      "Extreme fatigue & low energy",
      "Sexual dysfunction & low libido",
      "Blurred vision",
      "Tingling or numbness in hands/feet",
      "Unexplained weight loss",
    ],
    benefits: [
      "Normalizes blood sugar levels",
      "Reduces insulin dependency",
      "Improves pancreatic function",
      "Reduces diabetic complications",
      "99% pure herbal formula",
      "Works for Type 1 & Type 2",
      "NAFDAC & FDA approved",
      "Tested on 1,509+ patients",
    ],
    faqs: [
      { q: "Does this product actually work?", a: "Yes! NMN Capsules have a 99% success rate. Over 1,509 people have used and testified about this product." },
      { q: "How many packs do I need?", a: "Normally one pack should be okay, but for critical or long-term cases we advise 2 or 3 months packs. That's why we give discounts on larger orders." },
      { q: "Does it have any side effects?", a: "No! This is a magic blend of 99% pure herbal product and plant extract to lower blood sugar. It has no chemicals in it." },
      { q: "Does it actually reverse diabetes?", a: "Yes! It effectively normalizes blood sugar in 99% of cases. Type 2 reversal is well-documented with natural approaches." },
      { q: "How do I use this product?", a: "Once delivered, the instruction with a special guide and food tips will be sent to you via WhatsApp, Email, or Text with persistent monitoring over phone." },
      { q: "Can I use it with my current drugs?", a: "No! Use it alone to see the effectiveness. Consult your doctor before stopping any prescribed medications." },
      { q: "Is this NAFDAC and FDA approved?", a: "100% approved. Registration number is printed on the product package." },
    ],
    testimonials: [
      { name: "Mrs. Nkechi A.", location: "Port Harcourt", text: "My sugar was at 350mg/dL. After 2 months, it's at 95. My doctor was shocked. I'm off metformin!", rating: 5 },
      { name: "Mr. Sule Y.", location: "Kaduna", text: "Type 2 diabetic for 8 years. Used the 3-bottle pack. Blood sugar normalized in 6 weeks. This is a miracle.", rating: 5 },
      { name: "Funmilayo O.", location: "Ogun", text: "My wounds were never healing. Since starting this treatment, everything is better. My energy is back!", rating: 5 },
    ],
  },
  {
    id: "infection",
    slug: "infection",
    name: "Infection Relief",
    tagline: "End Chronic Infections Permanently",
    heroHeadline: "The Ancient Way to Permanently Get Rid of Chronic Infections",
    heroSubheadline: "Say goodbye to drug-resistant infections — 100% herbal, 99.9% bacteria & virus killing rate",
    productName: "Herbal Infection Relief Pack",
    whatsappKeyword: "Infection Relief",
    color: "teal",
    icon: "ShieldAlert",
    images: [
      "/product_images/B-CLEAR.png",
      "/product_images/B04_GARLIC_OIL_SOFTGEL.png",
    ],
    educationalIntro: "Stop wasting money on antibiotics that don't work. Most infections keep coming back because you're treating them the wrong way. Many people struggle with infections that never fully go away, no matter how many times they're treated. That's because not all infections are caused by bacteria — and antibiotics only work on bacterial infections. Years of self-medication, overuse, and abuse of antibiotics have led to drug-resistant infections that no longer respond to conventional treatments.",
    rootCauses: [
      "Antibiotic resistance from years of overuse",
      "Self-medication & wrong treatment approach",
      "Treating viral infections with antibiotics (ineffective)",
      "Weakened immune system",
      "Unprotected sexual contact",
      "Poor hygiene & sanitation conditions",
      "Incomplete treatment courses",
    ],
    howItWorks: "Our Herbal Infection Relief Pack uses a combination of potent natural antimicrobials that kill bacteria, viruses, fungi, and parasites at a 99.9% rate — including drug-resistant strains that antibiotics cannot touch. The pack includes ingredients that cleanse blood waste, treat visceral viruses, and work as natural antibiotics that inhibit and kill many kinds of germs. It also relieves inflammation in the gynaecological and urinary systems while supporting overall immune function.",
    detailedBenefits: [
      { title: "Kills 99.9% of Pathogens", description: "Effective against drug-resistant staphylococcus aureus, gonorrhea, syphilis, candida albicans, and genital herpes." },
      { title: "Cleanses Blood Waste", description: "Eliminates blood impurities and treats conditions caused by visceral viruses lodged deep in the system." },
      { title: "Treats Gynaecological Issues", description: "Effective for vaginal inflammation, genital itching, PID, and other reproductive system infections." },
      { title: "Heals Urinary Infections", description: "Treats UTIs, reduces frequent urination, and eliminates burning sensations during urination." },
      { title: "Boosts Immunity & Detoxes", description: "Destroys bad bacteria while protecting good gut bacteria. Detoxifies heavy metals from the body." },
      { title: "Promotes Overall Healing", description: "Supports wound tissue recovery, improves skin health, and reduces cholesterol levels." },
    ],
    warningNote: "If antibiotics have failed you repeatedly, it's likely because you've been using the wrong treatment. Our herbal formula targets the infections that conventional medicine cannot touch.",
    pricingPacks: [
      { label: "Treatment Pack", bottles: 2, originalPrice: 71226, salePrice: 61226, description: "B-Clear & Garlic Oil — infection relief", recommended: true, includedProducts: ["1 B-Clear", "1 Garlic Oil"] },
    ],
    symptoms: [
      "Painful & smelly discharge",
      "Staphylococcus aureus infection",
      "Gonorrhea & Chlamydia",
      "Genital herpes & HPV",
      "STDs, PID & genital warts",
      "E-Coli infections",
      "Vaginal/penile discharge",
      "Pain during sex",
      "Frequent urination & burning",
      "Weak erection from infection",
      "Low sperm count & watery sperm",
    ],
    benefits: [
      "Kills 99.9% of bacteria & viruses",
      "Clears Staph, Gonorrhea, Herpes, Syphilis",
      "Treats gynaecological inflammation",
      "Relieves vaginal/genital itching",
      "Improves sperm quality",
      "Heals urinary tract infections",
      "Cleanses blood waste & detoxifies",
      "Boosts immunity & gut health",
      "Improves skin health",
      "100% natural antibiotics",
      "NAFDAC approved",
    ],
    faqs: [
      { q: "Why don't antibiotics work for me?", a: "Years of overuse and self-medication have made most bacteria antibiotic-resistant. Our herbal formula targets resistant strains that regular antibiotics can't kill." },
      { q: "Can it treat STDs?", a: "Yes. It's effective against gonorrhea, syphilis, chlamydia, herpes, HPV, E-Coli, and other STDs with a 99.9% killing rate." },
      { q: "How many bottles do I need?", a: "Mild/recent cases: 2 bottles. Recurring/moderate: 3 bottles. Severe/long-term: 4 bottles." },
      { q: "Is it safe for both men and women?", a: "Yes. The formula is designed for both male and female reproductive health conditions." },
      { q: "Does it have side effects?", a: "No side effects. 100% pure herbal extracts with natural antimicrobial properties." },
      { q: "Will the infection come back?", a: "Unlike antibiotics, our herbal formula provides a permanent cure by eliminating the infection at its root, not just suppressing symptoms." },
    ],
    testimonials: [
      { name: "Anonymous (F)", location: "Lagos", text: "I had discharge and Staph for 2 years. Tried every antibiotic. 2 bottles of this and I'm 100% clear. I cried with joy.", rating: 5 },
      { name: "Emeka T.", location: "Benin", text: "Gonorrhea that kept returning. Finally gone after this pack. My test came back negative. Incredible.", rating: 5 },
      { name: "Yetunde A.", location: "Abeokuta", text: "UTI kept coming back. This fixed it permanently. No more burning or pain. Life is good again!", rating: 5 },
    ],
  },
  {
    id: "joint-pain",
    slug: "joint-pain",
    name: "Joint Pain & Arthritis",
    tagline: "Move Freely, Live Without Pain",
    heroHeadline: "Natural Solutions to End Any Form of Joint Pain & Arthritis",
    heroSubheadline: "100% herbal joint relief — no painkillers, no surgery, no side effects",
    productName: "Joint & Arthritis Relief Pack",
    whatsappKeyword: "JOINT AND ARTHRITIS",
    color: "purple",
    icon: "Bone",
    images: [
      "/product_images/SPABUCTA_SPRAY.png",
      "/product_images/PANICEPT.png",
    ],
    educationalIntro: "If you're tired of the constant pain, stiffness, and discomfort — and you're searching for a natural, safe, and fast-working solution with zero side effects — then this could be the most important message you'll come across today. Life can be very unbearable and frustrating when you cannot carry out your daily activities without feeling pain. Whether it's climbing stairs, walking to the gate, or simply getting out of bed — joint pain, arthritis, and rheumatism can turn the simplest tasks into punishment.",
    rootCauses: [
      "Age-related cartilage deterioration",
      "Autoimmune disorders (rheumatoid arthritis)",
      "Previous injury or joint trauma",
      "Obesity & excess weight on joints",
      "Chronic inflammation",
      "Poor blood circulation to joints",
      "Calcium & mineral deficiency",
    ],
    howItWorks: "Our Joint & Arthritis Relief Pack is a well-researched herbal remedy that works by reducing inflammation in the joint tissues, promoting blood circulation to affected areas, and supporting the body's natural healing processes. It relieves pain fast while addressing the root causes — not just masking symptoms like painkillers do. The formula also helps build strong bones, stabilize blood pressure, and contributes to normal cardiovascular function.",
    detailedBenefits: [
      { title: "Fast Pain Relief", description: "Relieves joint pain, bone pain, and general body aches naturally without dependency on painkillers." },
      { title: "Reduces Swelling & Stiffness", description: "Targets inflammation at the source, reducing swelling and restoring comfortable movement." },
      { title: "Restores Mobility & Flexibility", description: "Helps you walk, climb stairs, and perform daily activities without fear or discomfort." },
      { title: "Treats Rheumatoid Arthritis", description: "Effective for all forms of rheumatism, cervical spondylitis, and lumbar muscle strain." },
      { title: "Builds Stronger Bones", description: "Supports calcium absorption, prevents osteoporosis, and reduces the incidence of bone disease." },
      { title: "Improves Cardiovascular Health", description: "Stabilizes blood pressure, supports muscle movement, and contributes to normal heart function." },
    ],
    warningNote: "Over 245,509 people have used and testified about this product. Relief is real — and it's possible. Don't give up.",
    pricingPacks: [
      { label: "Treatment Pack", bottles: 2, originalPrice: 63500, salePrice: 53500, description: "Spabucta Spray & Panicept — joint pain & arthritis relief", recommended: true, includedProducts: ["1 Spabucta Spray", "1 Panicept"] },
    ],
    symptoms: [
      "Constant joint pain that won't go away",
      "Morning stiffness lasting hours",
      "Swollen, tender joints",
      "Cannot climb stairs without holding the rail",
      "Pain that wakes you at night",
      "Limited movement & flexibility loss",
      "Knee, hip, back, or shoulder pain",
      "Dependence on painkillers with no lasting relief",
    ],
    benefits: [
      "Relieves joint pain fast & naturally",
      "Reduces swelling & inflammation",
      "Restores flexibility & mobility",
      "Effective for rheumatoid arthritis",
      "Relieves cervical spondylitis",
      "Helps lumbar muscle strain & bone pains",
      "Promotes blood circulation",
      "Builds strong bones & teeth",
      "Helps prevent osteoporosis",
      "Stabilizes blood pressure",
      "NAFDAC & FDA approved",
    ],
    faqs: [
      { q: "Does the product work?", a: "Yes! It works 100%. Over 245,509 people have used and testified about this product." },
      { q: "Does it have any side effects?", a: "No! It's a magic blend of 100% pure herbal product and plant extract. It has no chemicals in it." },
      { q: "How many packs do I need?", a: "Normally one pack should be okay. But for critical issues, we advise 2 or 3 months packs. That's why we give huge discounts on larger orders." },
      { q: "Does it finally reverse joint/arthritis issues?", a: "Yes! It's done 100%. The formula addresses root causes, not just symptoms." },
      { q: "How do I use this product?", a: "Once delivered, the instruction with a special guide and food tips will be sent to you via WhatsApp or Email." },
      { q: "Can I use it with my current drugs?", a: "No! Use it alone to see the effectiveness." },
      { q: "Is this NAFDAC and FDA approved?", a: "100% approved. Registration number is printed on the product package." },
    ],
    testimonials: [
      { name: "Mama Chisom", location: "Owerri", text: "I couldn't walk to the kitchen without crying from pain. After 6 weeks, I danced at my granddaughter's naming ceremony. Thank you!", rating: 5 },
      { name: "Alhaji Danjuma", location: "Sokoto", text: "Knee pain for 7 years. Doctors said I needed replacement surgery. This product saved me from that. I walk freely now.", rating: 5 },
      { name: "Mrs. Adaeze N.", location: "Onitsha", text: "My rheumatoid arthritis was destroying my hands. After 3 months, I can hold a cup without pain. Incredible results.", rating: 5 },
    ],
  },
  {
    id: "blood-pressure",
    slug: "blood-pressure",
    name: "Blood Pressure",
    tagline: "Steady Pressure. Steady Life.",
    heroHeadline: "Take Control of Your Blood Pressure Naturally",
    heroSubheadline: "GHT BP Support + GHT Caerite — steady blood-pressure control + targeted heart protection",
    productName: "HBP Solution Pack",
    whatsappKeyword: "BP TREATMENT",
    color: "red",
    icon: "Heart",
    images: [
      "/product_images/A13_HYPERFREE.png",
      "/product_images/CAERITE.png",
      "/product_images/B-CLEAR.png",
    ],
    educationalIntro: "High blood pressure, often called the \"Silent Killer,\" affects millions of people without warning. Many don't even know they have it until it becomes life-threatening — causing strokes, heart attacks, kidney failure, and blindness. The good news is that lowering your blood pressure naturally is not only possible — it's simpler than you might think. With the right natural approach, you can protect your heart and restore your health.",
    rootCauses: [
      "Poor diet high in salt & processed foods",
      "Chronic stress & anxiety",
      "Obesity & lack of physical activity",
      "Excessive alcohol consumption",
      "Smoking & tobacco use",
      "Genetic predisposition & family history",
      "Underlying kidney or hormonal issues",
    ],
    howItWorks: "GHT BP Support + GHT Caerite provides steady blood-pressure control and targeted heart protection in one carefully packaged kit. The HBP Solution Pack is made up of strictly natural ingredients with no negative side effects. It carries prestigious certifications including the Kosher Seal (accepted by Jews who don't take anything that isn't 100% natural), Halal and Islamic seals, International Aloe Science Council certification, and Nigeria's own NAFDAC approval.",
    detailedBenefits: [
      { title: "Maintains Healthy Blood Pressure", description: "Supports stable readings and helps your body maintain healthy blood pressure levels naturally." },
      { title: "Improves Heart Circulation", description: "Enhances healthy blood flow to all organs, reducing strain on the cardiovascular system." },
      { title: "Reduces Symptoms", description: "Eliminates headaches, dizziness, chest tightness, and heart palpitations associated with hypertension." },
      { title: "Supports Heart Muscle Health", description: "Strengthens heart muscle, manages cholesterol levels, and improves cardiac output." },
      { title: "Boosts Energy & Sleep", description: "Customers report improved energy levels during the day and significantly better sleep quality at night." },
      { title: "Internationally Certified", description: "Carries Kosher, Halal, International Aloe Science Council, and NAFDAC seals — the highest form of purity assurance." },
    ],
    warningNote: "High blood pressure is called the 'Silent Killer' because you may not feel its effects until it's too late. Don't wait for a stroke or heart attack to take action.",
  pricingPacks: [
    { label: "Treatment Pack", bottles: 3, originalPrice: 115000, salePrice: 96130, description: "Hyperfree, Caerite & B-Clear — blood pressure control & heart protection", recommended: true, includedProducts: ["1 Hyperfree", "1 Caerite", "1 B-Clear"] },
  ],
    symptoms: [
      "Consistently high blood pressure readings",
      "Frequent & severe headaches",
      "Dizziness & blurred vision",
      "Chest tightness & heart palpitations",
      "Shortness of breath during normal activities",
      "Nose bleeds",
      "Poor sleep quality & restlessness",
      "Fatigue & low energy",
    ],
    benefits: [
      "Normalizes blood pressure readings",
      "Improves blood circulation to organs",
      "Reduces headaches & dizziness",
      "Supports heart muscle health",
      "Manages cholesterol naturally",
      "Boosts energy & sleep quality",
      "Detoxifies body systems",
      "Kosher, Halal & NAFDAC certified",
      "Safe for long-term use",
    ],
    faqs: [
      { q: "Can I stop my blood pressure medication?", a: "Don't stop abruptly. Many customers gradually reduce medication as BP normalizes. Always consult your doctor." },
      { q: "How long until my BP normalizes?", a: "Most customers see improvement within 3–4 weeks. For stable long-term control, use for 2–3 months." },
      { q: "Is it safe with heart conditions?", a: "Yes. It's formulated to support heart health. However, inform your cardiologist if you have a diagnosed heart condition." },
      { q: "What certifications does this have?", a: "Kosher seal, Halal seal, International Aloe Science Council, and NAFDAC Nigeria registration — seals of the highest form of purity." },
      { q: "Does it work for both systolic and diastolic hypertension?", a: "Yes. It helps normalize both numbers and improves overall cardiovascular health." },
      { q: "How do I use this product?", a: "Once delivered, you'll receive a detailed instruction guide with usage directions, food tips, and lifestyle support sent directly via WhatsApp." },
      { q: "Can I use it with my current medications?", a: "For best results, we recommend using the pack alone. If on prescribed drugs, kindly consult your doctor before use." },
    ],
    testimonials: [
      { name: "Bro. Festus O.", location: "Delta", text: "BP was 180/110 for 3 years. After 2 months on this pack, I'm at 128/82. My doctor is monitoring me to reduce my medication.", rating: 5 },
      { name: "Mrs. Zainab I.", location: "Katsina", text: "I had constant headaches from hypertension. They stopped in the second week. This product is a lifesaver.", rating: 5 },
      { name: "Mr. Anthony O.", location: "Cross River", text: "Both my wife and I use the BP pack. We've maintained healthy readings for 6 months now without side effects.", rating: 5 },
    ],
  },
  {
    id: "ulcer",
    slug: "ulcer",
    name: "Ulcer Relief",
    tagline: "Natural Healing for Gastric Health",
    heroHeadline: "Permanent Relief from Stomach Ulcers Naturally",
    heroSubheadline: "100% herbal Ulcer Relief Pack — eliminates pain, heals the stomach lining, and prevents recurrence",
    productName: "Ulcer Care Pack",
    whatsappKeyword: "ULCER TREATMENT",
    color: "emerald",
    icon: "Leaf",
    images: [
      "/product_images/STO_CARE.png",
      "/product_images/B04_GARLIC_OIL_SOFTGEL.png",
    ],
    educationalIntro: "Stomach ulcers are painful sores in the stomach lining that can make eating and daily life a nightmare. Often caused by H. pylori bacteria or long-term use of anti-inflammatory drugs, ulcers can lead to severe complications if left untreated. Our natural approach focuses on eliminating the root cause and promoting the regeneration of the stomach lining.",
    rootCauses: [
      "H. pylori bacterial infection",
      "Long-term use of NSAIDs (painkillers)",
      "Excessive stomach acid production",
      "Chronic stress & poor diet",
      "Smoking & alcohol consumption",
    ],
    howItWorks: "The Ulcer Care Pack works by neutralizing excess acid, coating the stomach lining to protect it from further irritation, and using potent herbal extracts to kill H. pylori bacteria. It stimulates the body's natural healing process to repair the damaged tissues, providing permanent relief without the side effects of conventional antacids.",
    detailedBenefits: [
      { title: "Heals Stomach Lining", description: "Promotes the regeneration of healthy tissue in the stomach and intestinal lining." },
      { title: "Eliminates H. Pylori", description: "Natural antimicrobial properties target and kill the bacteria responsible for most ulcers." },
      { title: "Fast Pain Relief", description: "Quickly soothes burning sensations and abdominal pain associated with ulcers." },
      { title: "Prevents Recurrence", description: "Strengthens the stomach's natural defenses to prevent ulcers from returning." },
    ],
  pricingPacks: [
    { label: "Treatment Pack", bottles: 2, originalPrice: 70000, salePrice: 58596, description: "Sto-Care & Garlic Oil Softgel — complete ulcer healing", recommended: true, includedProducts: ["1 Sto-Care", "1 Garlic Oil Softgel"] },
  ],
    symptoms: [
      "Burning stomach pain",
      "Frequent bloating and burping",
      "Nausea or vomiting",
      "Heartburn or acid reflux",
      "Loss of appetite & weight loss",
    ],
    benefits: [
      "Permanent relief from ulcer pain",
      "Heals stomach & duodenal ulcers",
      "Eliminates H. pylori naturally",
      "Improves digestion & nutrient absorption",
      "100% herbal — safe and effective",
    ],
    faqs: [
      { q: "How long before I see results?", a: "Most users feel significant relief from pain within 7-14 days. Complete healing typically takes 1-2 months." },
      { q: "Does it work for chronic ulcers?", a: "Yes, our formula is specifically designed to address long-standing and recurring ulcer conditions." },
      { q: "Can I use it with antacids?", a: "Our formula is self-sufficient, but you can consult your doctor if you're currently taking other medications." },
    ],
    testimonials: [
      { name: "John D.", location: "Lagos", text: "I struggled with ulcers for 5 years. This pack changed my life. No more pain!", rating: 5 },
      { name: "Sarah O.", location: "Ibadan", text: "Truly effective. I can now eat spicy food again without any issues. Thank you!", rating: 5 },
    ],
  },
  {
    id: "cancer",
    slug: "cancer",
    name: "Cancer Support",
    tagline: "Immune-Boosting Herbal Support",
    heroHeadline: "Natural Immune Support for Cancer Prevention & Recovery",
    heroSubheadline: "B-Clear, Myco Balance & Garlic Oil — immune-boosting herbal support for prevention, treatment support, and recovery",
    productName: "Cancer Support Pack",
    whatsappKeyword: "CANCER SUPPORT",
    color: "indigo",
    icon: "Shield",
    images: [
      "/product_images/B-CLEAR.png",
      "/product_images/B04_GARLIC_OIL_SOFTGEL.png",
      "/product_images/MYCO-BALANCE.png",
    ],
    educationalIntro: "Cancer occurs when abnormal cells grow uncontrollably, damaging healthy tissue. While conventional treatments are often necessary, they weaken the immune system. Natural herbal support boosts immunity, reduces inflammation, and helps the body fight back — especially during and after conventional treatment.",
    rootCauses: [
      "Weakened immune system unable to detect abnormal cells",
      "Chronic inflammation & oxidative stress",
      "Exposure to carcinogens (tobacco, chemicals, radiation)",
      "Poor diet lacking antioxidants & essential nutrients",
      "Genetic predisposition & family history",
      "Viral infections (HPV, Hepatitis B/C) linked to certain cancers",
    ],
    howItWorks: "Our Cancer Support Pack combines three powerful immune-modulating products. B-Clear purifies the blood and supports immune function. GHT Myco Balance Softgel uses mycelium-based compounds for immune modulation. Garlic Oil Softgel provides natural antimicrobial and antioxidant protection. Together, they support the body's natural defense mechanisms during prevention, treatment, and recovery.",
    detailedBenefits: [
      { title: "Boosts Immune Function", description: "Strengthens the body's natural defense system to identify and combat abnormal cell growth." },
      { title: "Purifies Blood & Detoxifies", description: "B-Clear eliminates blood impurities and toxins that contribute to cellular damage." },
      { title: "Reduces Oxidative Stress", description: "Powerful antioxidants neutralize free radicals that damage DNA and promote cancer development." },
      { title: "Anti-Inflammatory Support", description: "Reduces chronic inflammation, a known driver of cancer progression." },
      { title: "Natural Antimicrobial", description: "Garlic Oil provides broad-spectrum antimicrobial protection against pathogens." },
      { title: "Supports Recovery", description: "Aids the body during and after conventional treatment by rebuilding immune strength." },
    ],
    warningNote: "This is a complementary support therapy, not a replacement for conventional cancer treatment. Always consult your oncologist before adding supplements.",
  pricingPacks: [
    { label: "Treatment Pack", bottles: 3, originalPrice: 103000, salePrice: 86226, description: "B-Clear, Garlic Oil Softgel & Myco Balance — immune-boosting cancer support", recommended: true, includedProducts: ["1 B-Clear", "1 Garlic Oil Softgel", "1 Myco Balance"] },
  ],
    symptoms: [
      "Unexplained weight loss",
      "Persistent fatigue & weakness",
      "Chronic pain that won't go away",
      "Unusual lumps or swelling",
      "Changes in skin (darkening, yellowing, sores that won't heal)",
      "Persistent cough or difficulty breathing",
      "Frequent infections due to weakened immunity",
    ],
    benefits: [
      "Strengthens immune system naturally",
      "Purifies blood & detoxifies body",
      "Reduces oxidative stress & free radicals",
      "Anti-inflammatory support",
      "Natural antimicrobial protection",
      "Supports recovery after treatment",
      "100% herbal — no side effects",
      "NAFDAC approved",
    ],
    faqs: [
      { q: "Can this cure cancer?", a: "This is a complementary support product, not a cancer cure. It strengthens the immune system and supports the body during treatment. Always consult your oncologist." },
      { q: "Can I take this during chemotherapy?", a: "Many customers use it alongside treatment, but you must inform your oncologist before adding any supplements." },
      { q: "How long before I notice improvements?", a: "Immune support benefits are typically felt within 2–4 weeks. Full benefits develop over 2–3 months." },
      { q: "Does it have side effects?", a: "No. 100% pure herbal formula with no chemicals. Safe for long-term use." },
      { q: "Is it NAFDAC approved?", a: "Yes. All products in the pack are NAFDAC registered and approved." },
      { q: "How do I use this product?", a: "Once delivered, detailed instructions along with a special guide and food tips will be sent to you via WhatsApp or Email." },
    ],
    testimonials: [
      { name: "Mrs. Adebayo F.", location: "Lagos", text: "After my chemo sessions, my immunity was very low. This pack helped me regain strength. My doctor noticed the improvement.", rating: 5 },
      { name: "Mr. Ibrahim K.", location: "Abuja", text: "I use this for prevention since cancer runs in my family. My immune markers have improved significantly.", rating: 5 },
      { name: "Chioma N.", location: "Owerri", text: "Supportive care that actually works. I feel stronger and more energetic during my recovery.", rating: 5 },
    ],
  },
  {
    id: "female-infertility",
    slug: "female-infertility",
    name: "Female Infertility",
    tagline: "Restore Fertility Naturally",
    heroHeadline: "Overcome Female Infertility & Restore Your Fertility Naturally",
    heroSubheadline: "Female Care, Longzit, B-Clear & Ganoderma — hormonal balance, reproductive health & ovulation support",
    productName: "Female Fertility Pack",
    whatsappKeyword: "FEMALE INFERTILITY",
    color: "pink",
    icon: "Heart",
    images: [
      "/product_images/LONGZIT.png",
      "/product_images/FEMALE_CARE.png",
      "/product_images/GANODERMA_REISHI_3_IN_1.png",
    ],
    educationalIntro: "Female infertility affects millions of women across Nigeria. It can be devastating — causing emotional distress, relationship strain, and social stigma. The causes range from hormonal imbalances and ovulation disorders to blocked fallopian tubes and poor egg quality. Many causes of female infertility can be addressed naturally with the right herbal support.",
    rootCauses: [
      "Hormonal imbalances (estrogen/progesterone irregularities)",
      "Polycystic Ovary Syndrome (PCOS)",
      "Blocked or damaged fallopian tubes",
      "Poor egg quality & ovarian reserve decline",
      "Endometriosis & uterine fibroids",
      "Chronic infections affecting reproductive organs",
      "Stress, poor diet & nutritional deficiencies",
    ],
    howItWorks: "The Female Fertility Pack combines four synergistic herbal products. Female Care supports hormonal balance and ovulation. Longzit provides systemic hormonal regulation. B-Clear purifies the blood and eliminates toxins that impair reproductive function. GHT Ganoderma Softgel provides immune and hormonal modulation. Together, they address the root causes of infertility.",
    detailedBenefits: [
      { title: "Restores Hormonal Balance", description: "Regulates estrogen and progesterone levels for regular, healthy ovulation cycles." },
      { title: "Supports Ovulation", description: "Female Care specifically promotes regular ovulation, increasing chances of conception." },
      { title: "Purifies Reproductive System", description: "B-Clear eliminates blood impurities and toxins that can block fallopian tubes or impair egg quality." },
      { title: "Reduces Inflammation", description: "Ganoderma reduces reproductive organ inflammation, supporting healing of endometriosis and fibroids." },
      { title: "Improves Egg Quality", description: "Antioxidant-rich formula supports healthy egg development and ovarian function." },
      { title: "Boosts Overall Vitality", description: "Enhances energy, reduces stress, and supports the body's overall readiness for pregnancy." },
    ],
    warningNote: "If you have been trying to conceive for over 12 months without success, this natural approach can help. However, severe structural issues may require medical intervention.",
  pricingPacks: [
    { label: "Treatment Pack", bottles: 3, originalPrice: 102000, salePrice: 85650, description: "Longzit, Female Care & Ganoderma Reishi — fertility restoration", recommended: true, includedProducts: ["1 Longzit", "1 Female Care", "1 Ganoderma Reishi"] },
  ],
    symptoms: [
      "Irregular or absent menstrual periods",
      "Inability to conceive after 12+ months of trying",
      "Hormonal acne or excessive facial hair",
      "Painful or heavy periods",
      "Recurrent miscarriages",
      "Unusual discharge or pelvic pain",
      "Weight gain especially around the midsection",
    ],
    benefits: [
      "Restores hormonal balance naturally",
      "Promotes regular ovulation",
      "Purifies blood & reproductive system",
      "Reduces reproductive inflammation",
      "Improves egg quality",
      "Supports uterine health",
      "Boosts overall vitality & energy",
      "100% herbal — no side effects",
      "NAFDAC approved",
    ],
    faqs: [
      { q: "Can this help me get pregnant?", a: "Many women have conceived after using this pack. It addresses hormonal imbalance, poor ovulation, and reproductive toxicity. Results vary by individual." },
      { q: "How long before I see results?", a: "Hormonal balance improvements are typically noticed within 4–6 weeks. For conception, we recommend consistent use for 3–6 months." },
      { q: "Does it work for PCOS?", a: "Yes. The formula specifically targets hormonal imbalances associated with PCOS, promoting regular ovulation." },
      { q: "Can I use it with fertility drugs?", a: "We recommend using it alone for best results. Consult your doctor if currently on fertility medications." },
      { q: "Does it have side effects?", a: "No. 100% pure herbal formula with no chemicals. Safe for long-term use." },
      { q: "How do I use this product?", a: "Once delivered, detailed instructions along with a special guide and food tips will be sent to you via WhatsApp or Email." },
    ],
    testimonials: [
      { name: "Mrs. Amaka O.", location: "Enugu", text: "After 3 years of trying, I conceived within 4 months of using the Female Fertility Pack. I'm holding my baby girl right now!", rating: 5 },
      { name: "Fatima M.", location: "Kano", text: "My periods were completely irregular for years. After 2 months, my cycle normalized. I feel hopeful again.", rating: 5 },
      { name: "Blessing A.", location: "Benin", text: "PCOS made me think I could never have children. This pack proved me wrong. Currently 5 months pregnant!", rating: 5 },
    ],
  },
  {
    id: "hemorrhoid-pile",
    slug: "hemorrhoid-pile",
    name: "Hemorrhoid (Pile)",
    tagline: "End Pile Pain & Discomfort",
    heroHeadline: "Treat Hemorrhoids & Piles Naturally — No Surgery Needed",
    heroSubheadline: "Ganoderma Softgel & Constifree Tea — anti-inflammatory & digestive regulation for lasting relief",
    productName: "Hemorrhoid Relief Pack",
    whatsappKeyword: "HEMORRHOID TREATMENT",
    color: "amber",
    icon: "Droplet",
    images: [
      "/product_images/GANODERMA_REISHI_3_IN_1.png",
      "/product_images/CONSTIFREE.png",
    ],
    educationalIntro: "Hemorrhoids (piles) are swollen veins in the rectum and anus that cause pain, bleeding, itching, and extreme discomfort during bowel movements. They affect millions of Nigerians, especially adults over 30. The main cause is chronic constipation and straining. Left untreated, they can worsen, leading to thrombosis, severe bleeding, and the need for painful surgery. But surgery is NOT your only option.",
    rootCauses: [
      "Chronic constipation & straining during bowel movements",
      "Low fiber diet & dehydration",
      "Sedentary lifestyle & prolonged sitting",
      "Obesity & excess weight",
      "Pregnancy & childbirth",
      "Heavy lifting & physical strain",
    ],
    howItWorks: "The Hemorrhoid Relief Pack uses two complementary herbal products. GHT Ganoderma Softgel (Reishi 3-in-1) provides powerful anti-inflammatory action — reducing swelling of hemorrhoidal veins and promoting tissue healing. Constifree Tea regulates digestion and eliminates constipation — the primary cause of hemorrhoids. By addressing both the symptom and the root cause, this pack provides lasting relief without surgery.",
    detailedBenefits: [
      { title: "Reduces Swelling & Inflammation", description: "Ganoderma's anti-inflammatory properties shrink swollen hemorrhoidal veins and reduce pain." },
      { title: "Eliminates Constipation", description: "Constifree Tea regulates bowel movements naturally, eliminating the straining that causes hemorrhoids." },
      { title: "Stops Bleeding", description: "Promotes healing of damaged rectal tissue and stops bleeding during bowel movements." },
      { title: "Relieves Pain & Itching", description: "Soothes the burning, itching, and discomfort associated with both internal and external hemorrhoids." },
    ],
    warningNote: "If you're experiencing severe rectal bleeding, consult a doctor immediately to rule out other conditions. This product is for hemorrhoid treatment and should not replace medical evaluation for serious symptoms.",
  pricingPacks: [
    { label: "Treatment Pack", bottles: 2, originalPrice: 58000, salePrice: 48700, description: "Constifree Tea & Ganoderma — hemorrhoid relief without surgery", recommended: true, includedProducts: ["1 Constifree Tea", "1 Ganoderma"] },
  ],
    symptoms: [
      "Pain during bowel movements",
      "Bright red blood on toilet paper or in stool",
      "Itching & irritation around the anus",
      "Swelling or lump near the anus",
      "Discomfort when sitting",
      "Mucus discharge after bowel movements",
    ],
    benefits: [
      "Reduces hemorrhoid swelling naturally",
      "Eliminates constipation & straining",
      "Stops rectal bleeding",
      "Relieves pain & itching",
      "No surgery required",
      "100% herbal — no side effects",
      "NAFDAC approved",
    ],
    faqs: [
      { q: "Can this treat hemorrhoids without surgery?", a: "Yes. By addressing the root cause (constipation) and reducing inflammation, most hemorrhoids heal naturally without surgical intervention." },
      { q: "How long before I see relief?", a: "Most users experience significant pain reduction within 1–2 weeks. Complete healing typically takes 1–2 months." },
      { q: "Does it work for both internal and external hemorrhoids?", a: "Yes. The formula is effective for both types, as well as thrombosed hemorrhoids." },
      { q: "Does it have side effects?", a: "No. 100% pure herbal formula. Safe for long-term use." },
      { q: "How do I use this product?", a: "Once delivered, detailed instructions along with a special guide and food tips will be sent to you via WhatsApp or Email." },
    ],
    testimonials: [
      { name: "Mr. Chinedu O.", location: "Abia", text: "I was in so much pain I couldn't sit properly. After 3 weeks, the swelling reduced dramatically. No surgery needed!", rating: 5 },
      { name: "Mama Halima", location: "Sokoto", text: "Constifree Tea changed everything. No more straining, no more bleeding. I'm finally comfortable again.", rating: 5 },
      { name: "Auntie Bimpe", location: "Oyo", text: "Years of piles, gone in 2 months. I wish I found this earlier. Highly recommend to anyone suffering.", rating: 5 },
    ],
  },
  {
    id: "hepatitis",
    slug: "hepatitis",
    name: "Hepatitis",
    tagline: "Restore Liver Health Naturally",
    heroHeadline: "Treat Hepatitis & Restore Liver Function Naturally",
    heroSubheadline: "B-Clear, I-Detox Tea & Livities — comprehensive liver restoration for hepatitis",
    productName: "Hepatitis Treatment Pack",
    whatsappKeyword: "HEPATITIS TREATMENT",
    color: "yellow",
    icon: "AlertTriangle",
    images: [
      "/product_images/B-CLEAR.png",
      "/product_images/I-DETOX_TEA.png",
      "/product_images/LIVITIES.png",
    ],
    educationalIntro: "Hepatitis is an inflammation of the liver, most commonly caused by viral infections (Hepatitis B and C). It can lead to liver cirrhosis, liver failure, and even liver cancer if left untreated. In Nigeria, Hepatitis B is particularly prevalent, with millions of carriers unaware of their status. The virus silently damages the liver over years, often showing no symptoms until significant damage has occurred.",
    rootCauses: [
      "Hepatitis B & C viral infections",
      "Excessive alcohol consumption",
      "Autoimmune disorders",
      "Exposure to toxic chemicals & drugs",
      "Poor diet high in processed foods & sugar",
      "Unprotected sexual contact & contaminated blood",
    ],
    howItWorks: "Our Hepatitis Treatment Pack is the most comprehensive liver restoration formula available. B-Clear targets blood purification and hepatitis virus suppression. Sto-Care repairs liver tissue. GHT Ganoderma Softgel provides antiviral and immune modulation. GHT Myco Balance Softgel supports liver regeneration. Livities Tablet is the primary liver function restoration agent. I-Detox Tea provides daily liver detoxification and cleansing.",
    detailedBenefits: [
      { title: "Suppresses Hepatitis Virus", description: "B-Clear's blood purification properties target and suppress Hepatitis B and C viral activity." },
      { title: "Repairs Liver Tissue", description: "Sto-Care and Livities Tablet support the regeneration of damaged liver cells and restore function." },
      { title: "Antiviral Protection", description: "Ganoderma provides natural antiviral compounds that help the body fight hepatitis viruses." },
      { title: "Liver Regeneration", description: "Myco Balance supports mycelium-based liver cell regeneration for long-term recovery." },
      { title: "Daily Detoxification", description: "I-Detox Tea provides gentle daily liver cleansing, removing toxins and supporting bile production." },
      { title: "Restores Liver Enzymes", description: "Helps normalize ALT, AST, and other liver enzyme levels — a key marker of hepatitis recovery." },
    ],
    warningNote: "Hepatitis can progress silently for years. If you have been diagnosed with Hepatitis B or C, early treatment gives the best outcomes. Don't wait until cirrhosis develops.",
  pricingPacks: [
    { label: "Treatment Pack", bottles: 3, originalPrice: 113000, salePrice: 94320, description: "B-Clear, I-Detox Tea & Livities — complete hepatitis treatment", recommended: true, includedProducts: ["1 B-Clear", "1 I-Detox Tea", "1 Livities"] },
  ],
    symptoms: [
      "Yellowing of skin & eyes (jaundice)",
      "Dark urine & pale stools",
      "Fatigue & chronic weakness",
      "Abdominal pain & swelling",
      "Loss of appetite & nausea",
      "Elevated liver enzymes (ALT/AST)",
      "Joint pain & unexplained fever",
    ],
    benefits: [
      "Suppresses Hepatitis B & C virus",
      "Repairs damaged liver tissue",
      "Provides antiviral protection",
      "Supports liver cell regeneration",
      "Daily liver detoxification",
      "Normalizes liver enzyme levels",
      "100% herbal — no side effects",
      "NAFDAC approved",
    ],
    faqs: [
      { q: "Can this cure Hepatitis B or C?", a: "Many customers have seen significant improvement in liver function and viral load reduction. Results vary by individual and severity." },
      { q: "How long before liver enzymes normalize?", a: "Most users see improvement in liver enzyme levels within 4–8 weeks. Full recovery can take 3–6 months." },
      { q: "Can I use it with antiviral medications?", a: "We recommend using it alone for best results. Consult your hepatologist if currently on antiviral therapy." },
      { q: "Does it work for both Hepatitis B and C?", a: "Yes. The formula targets liver inflammation and viral activity common to both types." },
      { q: "Does it have side effects?", a: "No. 100% pure herbal formula with no chemicals. Safe for long-term use." },
      { q: "How do I use this product?", a: "Once delivered, detailed instructions along with a special guide and food tips will be sent to you via WhatsApp or Email." },
    ],
    testimonials: [
      { name: "Mr. Okafor P.", location: "Anambra", text: "Diagnosed with Hepatitis B in 2021. After 4 months on this pack, my viral load dropped significantly. My doctor was impressed.", rating: 5 },
      { name: "Aisha B.", location: "Kaduna", text: "My liver enzymes were dangerously high. After 3 months, they're almost normal. I feel alive again.", rating: 5 },
      { name: "Mr. Etim J.", location: "Calabar", text: "Hepatitis C for 6 years. The I-Detox Tea and Livities have made a visible difference in my energy and skin color.", rating: 5 },
    ],
  },
  {
    id: "liver-disease",
    slug: "liver-disease",
    name: "Liver Disease",
    tagline: "Reverse Liver Damage Naturally",
    heroHeadline: "Reverse Liver Disease & Restore Liver Function Naturally",
    heroSubheadline: "B-Clear, Sto-Care, Myco Balance, Livities, Garlic Oil & I-Detox Tea — complete liver restoration system",
    productName: "Liver Restoration Pack",
    whatsappKeyword: "LIVER DISEASE",
    color: "amber",
    icon: "AlertCircle",
    images: [
      "/product_images/B-CLEAR.png",
      "/product_images/MYCO-BALANCE.png",
      "/product_images/LIVITIES.png",
    ],
    educationalIntro: "Liver disease encompasses a range of conditions including fatty liver, cirrhosis, and liver inflammation. The liver is your body's primary detoxification organ — when it's damaged, toxins build up and your entire health deteriorates. Fatty liver disease is increasingly common in Nigeria due to poor diet and lifestyle. The good news is that the liver has an incredible ability to regenerate — and with the right natural support, significant recovery is possible.",
    rootCauses: [
      "Excessive alcohol consumption",
      "Fatty liver from poor diet & obesity",
      "Viral hepatitis (B & C)",
      "Autoimmune liver conditions",
      "Drug-induced liver damage",
      "Exposure to environmental toxins",
    ],
    howItWorks: "The Liver Restoration Pack is a comprehensive 6-product system. B-Clear purifies the blood and removes toxins. Sto-Care repairs damaged liver tissue. GHT Myco Balance supports mycelium-based liver regeneration. Livities Tablet is the primary liver function restoration agent. Garlic Oil Softgel provides antimicrobial and antioxidant protection. I-Detox Tea provides daily liver detoxification and cleansing.",
    detailedBenefits: [
      { title: "Restores Liver Function", description: "Livities Tablet specifically targets liver cell regeneration and restores healthy liver function." },
      { title: "Detoxifies & Cleanses", description: "B-Clear and I-Detox Tea work together to remove toxins and reduce the liver's workload." },
      { title: "Repairs Damaged Tissue", description: "Sto-Care supports the repair of liver and digestive tissue damaged by disease or toxins." },
      { title: "Reduces Fatty Liver", description: "The combination helps break down fat deposits in the liver and supports healthy metabolism." },
      { title: "Antioxidant Protection", description: "Garlic Oil provides powerful antioxidants that protect liver cells from further damage." },
      { title: "Supports Regeneration", description: "Myco Balance promotes the growth of new, healthy liver cells to replace damaged ones." },
    ],
    warningNote: "Liver disease can progress to cirrhosis, which is irreversible. Early treatment gives the best outcomes. If you're experiencing jaundice or severe abdominal swelling, seek medical attention immediately.",
  pricingPacks: [
    { label: "Treatment Pack", bottles: 3, originalPrice: 110000, salePrice: 91580, description: "B-Clear, Myco Balance & Livities — complete liver restoration", recommended: true, includedProducts: ["1 B-Clear", "1 Myco Balance", "1 Livities"] },
  ],
    symptoms: [
      "Yellowing of skin & eyes (jaundice)",
      "Chronic fatigue & weakness",
      "Abdominal pain & swelling",
      "Dark urine & pale stools",
      "Swelling in legs & ankles",
      "Easy bruising & bleeding",
      "Loss of appetite & nausea",
    ],
    benefits: [
      "Restores liver function naturally",
      "Detoxifies & cleanses the liver",
      "Repairs damaged liver tissue",
      "Reduces fatty liver deposits",
      "Provides antioxidant protection",
      "Supports liver cell regeneration",
      "100% herbal — no side effects",
      "NAFDAC approved",
    ],
    faqs: [
      { q: "Can liver disease be reversed naturally?", a: "Yes, especially in early stages. The liver has remarkable regenerative capacity. Our pack supports this natural regeneration process." },
      { q: "How long before I see improvement?", a: "Most users notice improved energy and digestion within 2–4 weeks. Liver enzyme improvement typically shows in 6–8 weeks." },
      { q: "Does it work for fatty liver?", a: "Yes. The formula specifically helps break down fat deposits in the liver and supports healthy metabolism." },
      { q: "Can I use it if I have cirrhosis?", a: "The pack can provide supportive care for cirrhosis, but cirrhosis involves permanent scarring. Consult your hepatologist." },
      { q: "Does it have side effects?", a: "No. 100% pure herbal formula with no chemicals. Safe for long-term use." },
      { q: "How do I use this product?", a: "Once delivered, detailed instructions along with a special guide and food tips will be sent to you via WhatsApp or Email." },
    ],
    testimonials: [
      { name: "Alhaji Musa D.", location: "Kano", text: "Fatty liver for 3 years. After using the medium pack, my scan showed significant improvement. Doctor was surprised.", rating: 5 },
      { name: "Mrs. Oluwaseun A.", location: "Lagos", text: "I was always tired and my stomach was swollen. After 2 months, I feel like a new person. My liver is healing.", rating: 5 },
      { name: "Mr. Bassey E.", location: "Cross River", text: "Liver enzymes were 3x normal. After 3 months on this pack, they're almost back to normal. Incredible product.", rating: 5 },
    ],
  },
  {
    id: "stroke",
    slug: "stroke",
    name: "Stroke Recovery",
    tagline: "Recover & Prevent Strokes Naturally",
    heroHeadline: "Natural Stroke Recovery & Prevention Support",
    heroSubheadline: "Longzit & GHT Ginseng & Royal Jelly — blood circulation, nerve repair & cardiovascular protection",
    productName: "Stroke Recovery Pack",
    whatsappKeyword: "STROKE RECOVERY",
    color: "red",
    icon: "Activity",
    images: [
      "/product_images/LONGZIT.png",
      "/product_images/GINSENG_&_ROYAL_JELLY.png",
    ],
    educationalIntro: "A stroke occurs when blood flow to part of the brain is interrupted, causing brain cells to die. It is one of the leading causes of death and disability in Nigeria. Stroke survivors often face paralysis, speech difficulties, memory loss, and a long recovery process. Prevention is critical — and for those recovering, natural support can significantly improve outcomes by promoting blood circulation, nerve repair, and cardiovascular health.",
    rootCauses: [
      "High blood pressure (the #1 risk factor)",
      "Blocked or narrowed blood vessels (ischemic stroke)",
      "Weakened blood vessel rupture (hemorrhagic stroke)",
      "High cholesterol & atherosclerosis",
      "Diabetes & obesity",
      "Smoking & excessive alcohol consumption",
      "Irregular heartbeat (atrial fibrillation)",
    ],
    howItWorks: "The Stroke Recovery Pack combines two powerful products. Longzit supports blood circulation, reduces blood viscosity, and helps prevent clot formation — addressing the root cause of ischemic strokes. GHT Ginseng & Royal Jelly Softgel provides nerve repair support, boosts energy, and strengthens cardiovascular function. Together, they support both recovery from stroke damage and prevention of future episodes.",
    detailedBenefits: [
      { title: "Improves Blood Circulation", description: "Longzit enhances blood flow to the brain and throughout the body, supporting recovery and preventing clots." },
      { title: "Supports Nerve Repair", description: "Ginseng & Royal Jelly support the regeneration of nerve cells damaged by stroke." },
      { title: "Strengthens Cardiovascular System", description: "Improves heart function and blood vessel health, reducing the risk of recurrent strokes." },
      { title: "Boosts Energy & Vitality", description: "Royal Jelly provides essential nutrients that combat the chronic fatigue common in stroke recovery." },
    ],
    warningNote: "If you or someone is experiencing stroke symptoms (face drooping, arm weakness, speech difficulty), seek emergency medical attention immediately. This product is for recovery support and prevention, not acute stroke treatment.",
  pricingPacks: [
    { label: "Treatment Pack", bottles: 2, originalPrice: 46000, salePrice: 38100, description: "Longzit & Ginseng & Royal Jelly — stroke recovery & prevention", recommended: true, includedProducts: ["1 Longzit", "1 Ginseng & Royal Jelly"] },
  ],
    symptoms: [
      "Sudden numbness or weakness in face, arm, or leg (especially one side)",
      "Sudden confusion or trouble speaking",
      "Sudden vision problems in one or both eyes",
      "Sudden severe headache with no known cause",
      "Difficulty walking, dizziness, loss of balance",
      "High blood pressure readings",
      "History of mini-strokes (TIAs)",
    ],
    benefits: [
      "Improves blood circulation to the brain",
      "Supports nerve cell regeneration",
      "Strengthens cardiovascular system",
      "Reduces risk of recurrent strokes",
      "Boosts energy & combats fatigue",
      "Supports overall brain health",
      "100% herbal — no side effects",
      "NAFDAC approved",
    ],
    faqs: [
      { q: "Can this help after a stroke?", a: "Yes. The pack supports recovery by improving blood circulation, promoting nerve repair, and strengthening cardiovascular health." },
      { q: "How long before I see improvement?", a: "Circulation improvements are typically noticed within 2–4 weeks. Nerve repair and functional recovery take longer — 3–6 months of consistent use." },
      { q: "Can this prevent a second stroke?", a: "Yes. By improving blood circulation and cardiovascular health, the pack helps reduce risk factors for recurrent strokes." },
      { q: "Can I use it with blood thinners?", a: "Consult your doctor if currently on blood-thinning medications. We generally recommend using it alone for best results." },
      { q: "Does it have side effects?", a: "No. 100% pure herbal formula with no chemicals. Safe for long-term use." },
      { q: "How do I use this product?", a: "Once delivered, detailed instructions along with a special guide and food tips will be sent to you via WhatsApp or Email." },
    ],
    testimonials: [
      { name: "Chief Adeola S.", location: "Ibadan", text: "After my stroke, I couldn't move my left arm. After 3 months on this pack, I can hold a cup again. The improvement is real.", rating: 5 },
      { name: "Mrs. Kudirat B.", location: "Ilorin", text: "My husband had a stroke last year. The Royal Jelly has given him so much more energy. His speech is also improving.", rating: 5 },
      { name: "Mr. Udo E.", location: "Uyo", text: "I use this for prevention since my father died of stroke. My blood pressure is stable and I feel healthier overall.", rating: 5 },
    ],
  },
];

export const getProductBySlug = (slug: string): Product | undefined =>
  products.find((p) => p.slug === slug);
